### ISSUE TITLE
Question about group / dedup --per-gene

### ISSUE THREAD

**Issue by Simon-Coetzee** [CGATOxford/UMI-tools#131]
When I run the following command (or a similar dedup command):

`umi_tools group -I test.bam --per-gene --gene-transcript-map='gene2rapmap.tsv' --edit-distance-threshold=2 --group-out=test.bam.grouped.tsv --output-bam -S test.group.2.bam -L test.group.2.log --`

dedup command looks like this:
`umi_tools dedup -I test.bam --per-gene --gene-transcript-map='gene2rapmap.tsv' --edit-distance-threshold=2 -S test.dedup.2.bam -L test.dedup.2.log --`

where gene2rapmap.tsv looks like this:
```
ENSG00000223972.5       ENST00000456328.2|ENSG00000223972.5|OTTHUMG00000000961.2|OTTHUMT00000362751.1|DDX11L1-002|DDX11L1|1657|processed_transcript|
ENSG00000223972.5       ENST00000450305.2|ENSG00000223972.5|OTTHUMG00000000961.2|OTTHUMT00000002844.2|DDX11L1-001|DDX11L1|632|transcribed_unprocessed_pseudogene|
ENSG00000227232.5       ENST00000488147.1|ENSG00000227232.5|OTTHUMG00000000958.1|OTTHUMT00000002839.1|WASH7P-001|WASH7P|1351|unprocessed_pseudogene|
ENSG00000278267.1       ENST00000619216.1|ENSG00000278267.1|-|-|MIR6859-1-201|MIR6859-1|68|miRNA|
ENSG00000243485.5       ENST00000473358.1|ENSG00000243485.5|OTTHUMG00000000959.2|OTTHUMT00000002840.1|MIR1302-2HG-001|MIR1302-2HG|712|lincRNA|
ENSG00000243485.5       ENST00000469289.1|ENSG00000243485.5|OTTHUMG00000000959.2|OTTHUMT00000002841.2|MIR1302-2HG-002|MIR1302-2HG|535|lincRNA|
ENSG00000284332.1       ENST00000607096.1|ENSG00000284332.1|-|-|MIR1302-2-201|MIR1302-2|138|miRNA|
ENSG00000237613.2       ENST00000417324.1|ENSG00000237613.2|OTTHUMG00000000960.1|OTTHUMT00000002842.1|FAM138A-001|FAM138A|1187|lincRNA|
ENSG00000237613.2       ENST00000461467.1|ENSG00000237613.2|OTTHUMG00000000960.1|OTTHUMT00000002843.1|FAM138A-002|FAM138A|590|lincRNA|
ENSG00000268020.3       ENST00000606857.1|ENSG00000268020.3|OTTHUMG00000185779.1|OTTHUMT00000471235.1|OR4G4P-001|OR4G4P|840|unprocessed_pseudogene|
```

and the input bam (test.bam) looks like this:
```
NS500624:117:HMK7JBGX2:1:21312:21351:15400:CELL_ACGCCGACATTAACCG:UMI_GTCTTATGCA:SAMPLE_TAACAAGG:UID_TAACAAGGACGCCGACATTAACCGGTCTTATGCA  16      ENST00000456328.2|ENSG00000223972.5|OTTHUMG00000000961.2|OTTHUMT00000362751.1|DDX11L1-002|DDX11L1|1657|processed_transcript|    163     255     98M     *       0       0       CTGGCCTGTGCCAGGGTGCAAGCTGAGCACTGGAGTGGAGTTTCCCTGTGGAGAGGAGCCATGCCTAGAGTGGGATGGGCCATTGTTCATCTTCTGGC *       NH:i:4
NS500624:117:HMK7JBGX2:4:12612:17207:3409:CELL_AGTAGTCCACCGATAT:UMI_GCTACTGAGT:SAMPLE_TAACAAGG:UID_TAACAAGGAGTAGTCCACCGATATGCTACTGAGT   16      ENST00000456328.2|ENSG00000223972.5|OTTHUMG00000000961.2|OTTHUMT00000362751.1|DDX11L1-002|DDX11L1|1657|processed_transcript|    185     255     98M     *       0       0       CTGAGCACTGGAGTGGAGTTTTCCTGTGGAGAGGAGCCATGCCTAGAGTGGGATGGGCCATTGTTCATCTTCTGGCCCCTGTTGTCTGCATGTAACTT *       NH:i:4
NS500624:117:HMK7JBGX2:4:22604:24099:15539:CELL_ATCCGAAAGTGTCTCA:UMI_CGCAGGACAT:SAMPLE_TAACAAGG:UID_TAACAAGGATCCGAAAGTGTCTCACGCAGGACAT  16      ENST00000456328.2|ENSG00000223972.5|OTTHUMG00000000961.2|OTTHUMT00000362751.1|DDX11L1-002|DDX11L1|1657|processed_transcript|    242     255     98M     *       0       0       CCATTGTTCATCTTCTGGCCCCTGTTGTCTGCATGTAACTTAATACCACAACCAGGCATAGGGGAAAGATTGGAGGAAAGATGAGTGAGAGCATCAAC *       NH:i:3
NS500624:117:HMK7JBGX2:2:11102:6369:4141:CELL_CCTCACGAGGGTCTCC:UMI_GCATTATAAG:SAMPLE_TAACAAGG:UID_TAACAAGGCCTCACGAGGGTCTCCGCATTATAAG    0       ENST00000488147.1|ENSG00000227232.5|OTTHUMG00000000958.1|OTTHUMT00000002839.1|WASH7P-001|WASH7P|1351|unprocessed_pseudogene|    77      255     98M     *       0       0       GTCAGACCTATGCCGTGCCCTTCATCCAGCCAGACCTGCGGCGAGAGGAGGCCGTCCAGCAGCTGGCGGATGCCCTGCAGTACCTGCAGAAGGTCTCT *       NH:i:8
NS500624:117:HMK7JBGX2:3:22602:10740:6438:CELL_CATCAGATCATAAAGG:UMI_TCTTCTCAAC:SAMPLE_TAACAAGG:UID_TAACAAGGCATCAGATCATAAAGGTCTTCTCAAC   0       ENST00000488147.1|ENSG00000227232.5|OTTHUMG00000000958.1|OTTHUMT00000002839.1|WASH7P-001|WASH7P|1351|unprocessed_pseudogene|    104     255     98M     *       0       0       AGCCAGACCTGCGGCGAGAGGAGGCCGTCCAGCAGATGGTGGATGCCCTGCAGTACCTGCAGAAGGTCTCTGGAGCCATCTTCAGCAGCCAACAAATA *       NH:i:17
NS500624:117:HMK7JBGX2:2:13207:23509:9911:CELL_TGGTTAGTCACTTACT:UMI_GACTAACAGG:SAMPLE_TAACAAGG:UID_TAACAAGGTGGTTAGTCACTTACTGACTAACAGG   0       ENST00000488147.1|ENSG00000227232.5|OTTHUMG00000000958.1|OTTHUMT00000002839.1|WASH7P-001|WASH7P|1351|unprocessed_pseudogene|    175     255     98M     *       0       0       GCAGGATCTCCCAGCGGGTAGAGCAGAGCCGGAGCCAGGTGCAGGCCATTGGAGAGAAGGTCTCCTTGGCCCAGGCCAAGATTGAGAAGATCAAGGGC *       NH:i:31
NS500624:117:HMK7JBGX2:1:13104:5438:5434:CELL_CCTTCCCTGGGTCCCC:UMI_ACTAAGCCAG:SAMPLE_TAACAAGG:UID_TAACAAGGCCTTCCCTGGGTCCCCACTAAGCCAG    0       ENST00000488147.1|ENSG00000227232.5|OTTHUMG00000000958.1|OTTHUMT00000002839.1|WASH7P-001|WASH7P|1351|unprocessed_pseudogene|    301     255     98M     *       0       0       GTGCCAAGTACCCTGCTCCAGGGCGCCTGCAGGAATATGGCTCCATCTTCACGGGCGCCCAGGACCCTGGCCTGCAGAGACGCCCCCGCCACAGGGTC *       NH:i:2
NS500624:117:HMK7JBGX2:3:11401:2985:6544:CELL_CCTTCCCTGGGTCCCC:UMI_ACTAAGCCAG:SAMPLE_TAACAAGG:UID_TAACAAGGCCTTCCCTGGGTCCCCACTAAGCCAG    0       ENST00000488147.1|ENSG00000227232.5|OTTHUMG00000000958.1|OTTHUMT00000002839.1|WASH7P-001|WASH7P|1351|unprocessed_pseudogene|    396     255     98M     *       0       0       ATCCAGAGCAAGCACCGCCCCCTGGACGAGCGGGCCCTGCAGGAGAAGCTGAAGGACTTTCCTGTGTGCGTGAGCACCAAGCCGGAGCCCGAGGACGA *       NH:i:19
NS500624:117:HMK7JBGX2:3:23405:16647:18833:CELL_GTCACAGCATCACATG:UMI_GGTCTTTGTT:SAMPLE_TAACAAGG:UID_TAACAAGGGTCACAGCATCACATGGGTCTTTGTT  0       ENST00000488147.1|ENSG00000227232.5|OTTHUMG00000000958.1|OTTHUMT00000002839.1|WASH7P-001|WASH7P|1351|unprocessed_pseudogene|    429     255     98M     *       0       0       GCCCTGCAGGAGAAGCTGAAGGACTTTCCTGTGTGCGTGAGCACCAAGCCGGAGCCCGAGGACGATGCAGAAGAGGGACTTGGGGGTCTTCCCAGCAA *       NH:i:19
NS500624:117:HMK7JBGX2:3:13601:6317:1535:CELL_GGCTCGAAGCTCCTTC:UMI_GTCACACAGA:SAMPLE_TAACAAGG:UID_TAACAAGGGGCTCGAAGCTCCTTCGTCACACAGA    16      ENST00000488147.1|ENSG00000227232.5|OTTHUMG00000000958.1|OTTHUMT00000002839.1|WASH7P-001|WASH7P|1351|unprocessed_pseudogene|    552     255     98M     *       0       0       GGACCCCCATGTCGCCCCTGTAGGTACAAGAAGGATGTCTTCCTGGACCCCCTGGCTGGTGCTGTACCAAAGACCCATGTACTCTGCTTTGATTACAC *       NH:i:27
```

and the reads are from 10x chromium scRNA-seq, formatted with vals/umis, quasimapped with rapmap, I get results out on the other end that I don't quite understand. My expectation is that reads with the same gene/uid pairing will be either deduped or grouped, however I get results like this:

for dedup:
```
NS500624:117:HMK7JBGX2:1:13104:7177:19118:CELL_CTTCTCTGTCACACGC:UMI_TACGCCGCTC:SAMPLE_TAACAAGG:UID_TAACAAGGCTTCTCTGTCACACGCTACGCCGCTC   2304    ENST00000504434.1|ENSG00000146083.11|OTTHUMG00000130664.3|OTTHUMT00000372219.1|RNF44-004|RNF44|785|retained_intron|     592     255     98M     *       0       0       GCCGGCGGGAGCCCCCGAATGCTGCACCCAGCCACCCAGCAGAGCCCGGTCATGGGGGATCTCCACGAGCAGGTGCGCCAGGGACCTGTCCCTCTGTC *       NH:i:4  MC:Z:ENSG00000146083.11
NS500624:117:HMK7JBGX2:4:13406:21644:1183:CELL_CTTCTCTGTCACACGC:UMI_TACGCCGCTC:SAMPLE_TAACAAGG:UID_TAACAAGGCTTCTCTGTCACACGCTACGCCGCTC   0       ENST00000274811.8|ENSG00000146083.11|OTTHUMG00000130664.3|OTTHUMT00000253156.2|RNF44-001|RNF44|4155|protein_coding|     728     255     98M     *       0       0       AGGAGCGCCGAGCCTCGGCTCCTGCCGGCGGGAGCCCCCGAATGCTGCACCCAGCCACCCAGCAGAGCCCGTTCATGGTTGATCTCCACGAGCAGGTG *       NH:i:3  MC:Z:ENSG00000146083.11
NS500624:117:HMK7JBGX2:1:13104:7177:19118:CELL_CTTCTCTGTCACACGC:UMI_TACGCCGCTC:SAMPLE_TAACAAGG:UID_TAACAAGGCTTCTCTGTCACACGCTACGCCGCTC   0       ENST00000274811.8|ENSG00000146083.11|OTTHUMG00000130664.3|OTTHUMT00000253156.2|RNF44-001|RNF44|4155|protein_coding|     751     255     98M     *       0       0       GCCGGCGGGAGCCCCCGAATGCTGCACCCAGCCACCCAGCAGAGCCCGGTCATGGGGGATCTCCACGAGCAGGTGCGCCAGGGACCTGTCCCTCTGTC *       NH:i:4  MC:Z:ENSG00000146083.11
NS500624:117:HMK7JBGX2:2:23210:22337:12217:CELL_CTTCTCTGTCACACGC:UMI_TACGCCGCTC:SAMPLE_TAACAAGG:UID_TAACAAGGCTTCTCTGTCACACGCTACGCCGCTC  0       ENST00000274811.8|ENSG00000146083.11|OTTHUMG00000130664.3|OTTHUMT00000253156.2|RNF44-001|RNF44|4155|protein_coding|     831     255     98M     *       0       0       GGGACCTGTCCCTCTGTCCTACACGGTCACCACAGTGACGACCCAAGGCTTCCCCTTGCCTACAGGCCAGCACATCCCTGGAAACCACGGCAACCTGT *       NH:i:3  MC:Z:ENSG00000146083.11
NS500624:117:HMK7JBGX2:4:13406:21644:1183:CELL_CTTCTCTGTCACACGC:UMI_TACGCCGCTC:SAMPLE_TAACAAGG:UID_TAACAAGGCTTCTCTGTCACACGCTACGCCGCTC   2304    ENST00000513029.5|ENSG00000146083.11|OTTHUMG00000130664.3|OTTHUMT00000372217.1|RNF44-002|RNF44|1647|nonsense_mediated_decay|    481     255     98M     *       0       0       AGGAGCGCCGAGCCTCGGCTCCTGCCGGCGGGAGCCCCCGAATGCTGCACCCAGCCACCCAGCAGAGCCCGTTCATGGTTGATCTCCACGAGCAGGTG *       NH:i:3  MC:Z:ENSG00000146083.11
NS500624:117:HMK7JBGX2:1:13104:7177:19118:CELL_CTTCTCTGTCACACGC:UMI_TACGCCGCTC:SAMPLE_TAACAAGG:UID_TAACAAGGCTTCTCTGTCACACGCTACGCCGCTC   2304    ENST00000513029.5|ENSG00000146083.11|OTTHUMG00000130664.3|OTTHUMT00000372217.1|RNF44-002|RNF44|1647|nonsense_mediated_decay|    504     255     98M     *       0       0       GCCGGCGGGAGCCCCCGAATGCTGCACCCAGCCACCCAGCAGAGCCCGGTCATGGGGGATCTCCACGAGCAGGTGCGCCAGGGACCTGTCCCTCTGTC *       NH:i:4  MC:Z:ENSG00000146083.11
NS500624:117:HMK7JBGX2:2:23210:22337:12217:CELL_CTTCTCTGTCACACGC:UMI_TACGCCGCTC:SAMPLE_TAACAAGG:UID_TAACAAGGCTTCTCTGTCACACGCTACGCCGCTC  2304    ENST00000513029.5|ENSG00000146083.11|OTTHUMG00000130664.3|OTTHUMT00000372217.1|RNF44-002|RNF44|1647|nonsense_mediated_decay|    584     255     98M     *       0       0       GGGACCTGTCCCTCTGTCCTACACGGTCACCACAGTGACGACCCAAGGCTTCCCCTTGCCTACAGGCCAGCACATCCCTGGAAACCACGGCAACCTGT *       NH:i:3  MC:Z:ENSG00000146083.11
NS500624:117:HMK7JBGX2:2:11310:21286:17263:CELL_CTTCTCTGTCACACGC:UMI_TACGCCGCTC:SAMPLE_TAACAAGG:UID_TAACAAGGCTTCTCTGTCACACGCTACGCCGCTC  0       ENST00000504160.1|ENSG00000146083.11|OTTHUMG00000130664.3|OTTHUMT00000372218.1|RNF44-003|RNF44|887|nonsense_mediated_decay|     426     255     98M     *       0       0       ACTAGGTGGCCACCCTCCGCCCCCGTGGGCCAGCGGCGATTCTCTGCGGGACCTGGCAGCACCCCGGGCCAGCTCTGGGGAAGCCGCCGTCCCGACCT *       NH:i:1  MC:Z:ENSG00000146083.11
NS500624:117:HMK7JBGX2:3:23506:6775:14776:CELL_CTTCTCTGTCACACGC:UMI_TACGCCGCTC:SAMPLE_TAACAAGG:UID_TAACAAGGCTTCTCTGTCACACGCTACGCCGCTC   0       ENST00000504160.1|ENSG00000146083.11|OTTHUMG00000130664.3|OTTHUMT00000372218.1|RNF44-003|RNF44|887|nonsense_mediated_decay|     477     255     98M     *       0       0       CCTGGCCGCACCCCGGGCCAGCTCTGGGGAAGCCGCCGTCCCGACCTCCCCACCTCCCCGTAGAGGAGCGCCGAGCCTCGGCTCCGGCCGGCGGGAGC *       NH:i:1  MC:Z:ENSG00000146083.11
NS500624:117:HMK7JBGX2:4:13406:21644:1183:CELL_CTTCTCTGTCACACGC:UMI_TACGCCGCTC:SAMPLE_TAACAAGG:UID_TAACAAGGCTTCTCTGTCACACGCTACGCCGCTC   2304    ENST00000504160.1|ENSG00000146083.11|OTTHUMG00000130664.3|OTTHUMT00000372218.1|RNF44-003|RNF44|887|nonsense_mediated_decay|     540     255     98M     *       0       0       AGGAGCGCCGAGCCTCGGCTCCTGCCGGCGGGAGCCCCCGAATGCTGCACCCAGCCACCCAGCAGAGCCCGTTCATGGTTGATCTCCACGAGCAGGTG *       NH:i:3  MC:Z:ENSG00000146083.11
NS500624:117:HMK7JBGX2:1:13104:7177:19118:CELL_CTTCTCTGTCACACGC:UMI_TACGCCGCTC:SAMPLE_TAACAAGG:UID_TAACAAGGCTTCTCTGTCACACGCTACGCCGCTC   2304    ENST00000504160.1|ENSG00000146083.11|OTTHUMG00000130664.3|OTTHUMT00000372218.1|RNF44-003|RNF44|887|nonsense_mediated_decay|     563     255     98M     *       0       0       GCCGGCGGGAGCCCCCGAATGCTGCACCCAGCCACCCAGCAGAGCCCGGTCATGGGGGATCTCCACGAGCAGGTGCGCCAGGGACCTGTCCCTCTGTC *       NH:i:4  MC:Z:ENSG00000146083.11
NS500624:117:HMK7JBGX2:2:23210:22337:12217:CELL_CTTCTCTGTCACACGC:UMI_TACGCCGCTC:SAMPLE_TAACAAGG:UID_TAACAAGGCTTCTCTGTCACACGCTACGCCGCTC  2304    ENST00000504160.1|ENSG00000146083.11|OTTHUMG00000130664.3|OTTHUMT00000372218.1|RNF44-003|RNF44|887|nonsense_mediated_decay|     643     255     98M     *       0       0       GGGACCTGTCCCTCTGTCCTACACGGTCACCACAGTGACGACCCAAGGCTTCCCCTTGCCTACAGGCCAGCACATCCCTGGAAACCACGGCAACCTGT *       NH:i:3  MC:Z:ENSG00000146083.11
```
for group:
```
NS500624:117:HMK7JBGX2:1:13104:7177:19118:CELL_CTTCTCTGTCACACGC:UMI_TACGCCGCTC:SAMPLE_TAACAAGG:UID_TAACAAGGCTTCTCTGTCACACGCTACGCCGCTC   2304    ENST00000504434.1|ENSG00000146083.11|OTTHUMG00000130664.3|OTTHUMT00000372219.1|RNF44-004|RNF44|785|retained_intron|     592     255     98M     *       0       0       GCCGGCGGGAGCCCCCGAATGCTGCACCCAGCCACCCAGCAGAGCCCGGTCATGGGGGATCTCCACGAGCAGGTGCGCCAGGGACCTGTCCCTCTGTC *       NH:i:4  MC:Z:ENSG00000146083.11 UG:i:8031       BX:Z:TAACAAGGCTTCTCTGTCACACGCTACGCCGCTC
NS500624:117:HMK7JBGX2:4:13406:21644:1183:CELL_CTTCTCTGTCACACGC:UMI_TACGCCGCTC:SAMPLE_TAACAAGG:UID_TAACAAGGCTTCTCTGTCACACGCTACGCCGCTC   0       ENST00000274811.8|ENSG00000146083.11|OTTHUMG00000130664.3|OTTHUMT00000253156.2|RNF44-001|RNF44|4155|protein_coding|     728     255     98M     *       0       0       AGGAGCGCCGAGCCTCGGCTCCTGCCGGCGGGAGCCCCCGAATGCTGCACCCAGCCACCCAGCAGAGCCCGTTCATGGTTGATCTCCACGAGCAGGTG *       NH:i:3  MC:Z:ENSG00000146083.11 UG:i:8046       BX:Z:TAACAAGGCTTCTCTGTCACACGCTACGCCGCTC
NS500624:117:HMK7JBGX2:1:13104:7177:19118:CELL_CTTCTCTGTCACACGC:UMI_TACGCCGCTC:SAMPLE_TAACAAGG:UID_TAACAAGGCTTCTCTGTCACACGCTACGCCGCTC   0       ENST00000274811.8|ENSG00000146083.11|OTTHUMG00000130664.3|OTTHUMT00000253156.2|RNF44-001|RNF44|4155|protein_coding|     751     255     98M     *       0       0       GCCGGCGGGAGCCCCCGAATGCTGCACCCAGCCACCCAGCAGAGCCCGGTCATGGGGGATCTCCACGAGCAGGTGCGCCAGGGACCTGTCCCTCTGTC *       NH:i:4  MC:Z:ENSG00000146083.11 UG:i:8047       BX:Z:TAACAAGGCTTCTCTGTCACACGCTACGCCGCTC
NS500624:117:HMK7JBGX2:2:23210:22337:12217:CELL_CTTCTCTGTCACACGC:UMI_TACGCCGCTC:SAMPLE_TAACAAGG:UID_TAACAAGGCTTCTCTGTCACACGCTACGCCGCTC  0       ENST00000274811.8|ENSG00000146083.11|OTTHUMG00000130664.3|OTTHUMT00000253156.2|RNF44-001|RNF44|4155|protein_coding|     831     255     98M     *       0       0       GGGACCTGTCCCTCTGTCCTACACGGTCACCACAGTGACGACCCAAGGCTTCCCCTTGCCTACAGGCCAGCACATCCCTGGAAACCACGGCAACCTGT *       NH:i:3  MC:Z:ENSG00000146083.11 UG:i:8048       BX:Z:TAACAAGGCTTCTCTGTCACACGCTACGCCGCTC
NS500624:117:HMK7JBGX2:4:13406:21644:1183:CELL_CTTCTCTGTCACACGC:UMI_TACGCCGCTC:SAMPLE_TAACAAGG:UID_TAACAAGGCTTCTCTGTCACACGCTACGCCGCTC   2304    ENST00000513029.5|ENSG00000146083.11|OTTHUMG00000130664.3|OTTHUMT00000372217.1|RNF44-002|RNF44|1647|nonsense_mediated_decay|    481     255     98M     *       0       0       AGGAGCGCCGAGCCTCGGCTCCTGCCGGCGGGAGCCCCCGAATGCTGCACCCAGCCACCCAGCAGAGCCCGTTCATGGTTGATCTCCACGAGCAGGTG *       NH:i:3  MC:Z:ENSG00000146083.11 UG:i:8118       BX:Z:TAACAAGGCTTCTCTGTCACACGCTACGCCGCTC
NS500624:117:HMK7JBGX2:1:13104:7177:19118:CELL_CTTCTCTGTCACACGC:UMI_TACGCCGCTC:SAMPLE_TAACAAGG:UID_TAACAAGGCTTCTCTGTCACACGCTACGCCGCTC   2304    ENST00000513029.5|ENSG00000146083.11|OTTHUMG00000130664.3|OTTHUMT00000372217.1|RNF44-002|RNF44|1647|nonsense_mediated_decay|    504     255     98M     *       0       0       GCCGGCGGGAGCCCCCGAATGCTGCACCCAGCCACCCAGCAGAGCCCGGTCATGGGGGATCTCCACGAGCAGGTGCGCCAGGGACCTGTCCCTCTGTC *       NH:i:4  MC:Z:ENSG00000146083.11 UG:i:8119       BX:Z:TAACAAGGCTTCTCTGTCACACGCTACGCCGCTC
NS500624:117:HMK7JBGX2:2:23210:22337:12217:CELL_CTTCTCTGTCACACGC:UMI_TACGCCGCTC:SAMPLE_TAACAAGG:UID_TAACAAGGCTTCTCTGTCACACGCTACGCCGCTC  2304    ENST00000513029.5|ENSG00000146083.11|OTTHUMG00000130664.3|OTTHUMT00000372217.1|RNF44-002|RNF44|1647|nonsense_mediated_decay|    584     255     98M     *       0       0       GGGACCTGTCCCTCTGTCCTACACGGTCACCACAGTGACGACCCAAGGCTTCCCCTTGCCTACAGGCCAGCACATCCCTGGAAACCACGGCAACCTGT *       NH:i:3  MC:Z:ENSG00000146083.11 UG:i:8120       BX:Z:TAACAAGGCTTCTCTGTCACACGCTACGCCGCTC
NS500624:117:HMK7JBGX2:2:11310:21286:17263:CELL_CTTCTCTGTCACACGC:UMI_TACGCCGCTC:SAMPLE_TAACAAGG:UID_TAACAAGGCTTCTCTGTCACACGCTACGCCGCTC  0       ENST00000504160.1|ENSG00000146083.11|OTTHUMG00000130664.3|OTTHUMT00000372218.1|RNF44-003|RNF44|887|nonsense_mediated_decay|     426     255     98M     *       0       0       ACTAGGTGGCCACCCTCCGCCCCCGTGGGCCAGCGGCGATTCTCTGCGGGACCTGGCAGCACCCCGGGCCAGCTCTGGGGAAGCCGCCGTCCCGACCT *       NH:i:1  MC:Z:ENSG00000146083.11 UG:i:8130       BX:Z:TAACAAGGCTTCTCTGTCACACGCTACGCCGCTC
NS500624:117:HMK7JBGX2:3:23506:6775:14776:CELL_CTTCTCTGTCACACGC:UMI_TACGCCGCTC:SAMPLE_TAACAAGG:UID_TAACAAGGCTTCTCTGTCACACGCTACGCCGCTC   0       ENST00000504160.1|ENSG00000146083.11|OTTHUMG00000130664.3|OTTHUMT00000372218.1|RNF44-003|RNF44|887|nonsense_mediated_decay|     477     255     98M     *       0       0       CCTGGCCGCACCCCGGGCCAGCTCTGGGGAAGCCGCCGTCCCGACCTCCCCACCTCCCCGTAGAGGAGCGCCGAGCCTCGGCTCCGGCCGGCGGGAGC *       NH:i:1  MC:Z:ENSG00000146083.11 UG:i:8134       BX:Z:TAACAAGGCTTCTCTGTCACACGCTACGCCGCTC
NS500624:117:HMK7JBGX2:4:13406:21644:1183:CELL_CTTCTCTGTCACACGC:UMI_TACGCCGCTC:SAMPLE_TAACAAGG:UID_TAACAAGGCTTCTCTGTCACACGCTACGCCGCTC   2304    ENST00000504160.1|ENSG00000146083.11|OTTHUMG00000130664.3|OTTHUMT00000372218.1|RNF44-003|RNF44|887|nonsense_mediated_decay|     540     255     98M     *       0       0       AGGAGCGCCGAGCCTCGGCTCCTGCCGGCGGGAGCCCCCGAATGCTGCACCCAGCCACCCAGCAGAGCCCGTTCATGGTTGATCTCCACGAGCAGGTG *       NH:i:3  MC:Z:ENSG00000146083.11 UG:i:8137       BX:Z:TAACAAGGCTTCTCTGTCACACGCTACGCCGCTC
NS500624:117:HMK7JBGX2:1:13104:7177:19118:CELL_CTTCTCTGTCACACGC:UMI_TACGCCGCTC:SAMPLE_TAACAAGG:UID_TAACAAGGCTTCTCTGTCACACGCTACGCCGCTC   2304    ENST00000504160.1|ENSG00000146083.11|OTTHUMG00000130664.3|OTTHUMT00000372218.1|RNF44-003|RNF44|887|nonsense_mediated_decay|     563     255     98M     *       0       0       GCCGGCGGGAGCCCCCGAATGCTGCACCCAGCCACCCAGCAGAGCCCGGTCATGGGGGATCTCCACGAGCAGGTGCGCCAGGGACCTGTCCCTCTGTC *       NH:i:4  MC:Z:ENSG00000146083.11 UG:i:8138       BX:Z:TAACAAGGCTTCTCTGTCACACGCTACGCCGCTC
NS500624:117:HMK7JBGX2:2:23210:22337:12217:CELL_CTTCTCTGTCACACGC:UMI_TACGCCGCTC:SAMPLE_TAACAAGG:UID_TAACAAGGCTTCTCTGTCACACGCTACGCCGCTC  2304    ENST00000504160.1|ENSG00000146083.11|OTTHUMG00000130664.3|OTTHUMT00000372218.1|RNF44-003|RNF44|887|nonsense_mediated_decay|     643     255     98M     *       0       0       GGGACCTGTCCCTCTGTCCTACACGGTCACCACAGTGACGACCCAAGGCTTCCCCTTGCCTACAGGCCAGCACATCCCTGGAAACCACGGCAACCTGT *       NH:i:3  MC:Z:ENSG00000146083.11 UG:i:8139       BX:Z:TAACAAGGCTTCTCTGTCACACGCTACGCCGCTC
```

In both cases genes have the same gene / uid combination, however with `group`, unique `UG` tags are applied, and for `dedup` all reads are retained. Is this expected? Am I doing something wrong?

**Comment by IanSudbery** [comment]
Hi Simon,

You need `--per-contig` as well in your options to get the behaviour you want. @TomSmithCGAT Perhaps `--per-gene` was going to imply `--per-contig` (To be honest, I thought we'd already done this)

**Comment by TomSmithCGAT** [comment]
@IanSudbery. It shouldn't be neccessary to supply the --per-contig option as well. With the --per-gene and -gene-transcript-map options, _dedup_ will add the "meta-contig" tag (MC) to the reads as shown above. The deduplication should then proceed using the MC tag as the gene tag. I can't see any obvious reason why this doesn't work as expected.

@Simon-Coetzee, what version of UMI-tools are you using? If it's <0.4.4, could you check whether a version update resolves this. If its 0.4.4 would you be able to send the above files to me (tss38@cam.ac.uk). Just the top of the BAMs should be sufficient.

**Comment by TomSmithCGAT** [comment]
Ah ha. I think I have it. @Simon-Coetzee, I'll make a branch with a patch now.

**Comment by TomSmithCGAT** [comment]
@Simon-Coetzee. Would you mind installing from the {TS}-Patch_per_gene branch to see if this resolves the issue. I can give you instructions for installing from a branch if you would like?

**Comment by Simon-Coetzee** [comment]
@TomSmithCGAT, Thank you, I've got the branch installed and I'm running `dedup` now. If that works I'll check `group` and report back. Since I have you, is it possible to have dedup also place the `BX` tag in the bam? Or some other tag?

**Comment by Simon-Coetzee** [comment]
@TomSmithCGAT , so for `group`, I get this error now:
```
Traceback (most recent call last):
  File "/Users/coetzeesg/miniconda3/envs/umi-tools/bin/umi_tools", line 11, in <module>
    load_entry_point('umi-tools==0.4.4', 'console_scripts', 'umi_tools')()
  File "/Users/coetzeesg/miniconda3/envs/umi-tools/lib/python2.7/site-packages/umi_tools-0.4.4-py2.7.egg/umi_tools/umi_tools.py", line 46, in main
    module.main(sys.argv)
  File "/Users/coetzeesg/miniconda3/envs/umi-tools/lib/python2.7/site-packages/umi_tools-0.4.4-py2.7.egg/umi_tools/group.py", line 476, in main
    return_unmapped=options.output_unmapped):
  File "/Users/coetzeesg/miniconda3/envs/umi-tools/lib/python2.7/site-packages/umi_tools-0.4.4-py2.7.egg/umi_tools/umi_methods.py", line 333, in get_bundles
    if re.search(skip_regex, pos):
  File "/Users/coetzeesg/miniconda3/envs/umi-tools/lib/python2.7/re.py", line 146, in search
    return _compile(pattern, flags).search(string)
  File "/Users/coetzeesg/miniconda3/envs/umi-tools/lib/python2.7/re.py", line 247, in _compile
    raise TypeError, "first argument must be string or compiled pattern"
TypeError: first argument must be string or compiled pattern
```

**Comment by TomSmithCGAT** [comment]
Hi @Simon-Coetzee. Could you try re-installing the branch again. We didn't have any tests covering the per-gene option with group so this bug was missed previously. This should have been rectified now. 

Am I correct in thinking you are also ultimately using the per-gene option for "read counting"? I ask because, in the long term, we're considering removing the --per-gene options from _dedup_ and _group_. As far as we're aware, the only purpose of per-gene deduplication is to count the number of reads per gene so we have made a separate _count_ command to acheive exactly this. Restricting the use of the different commands should help clarify the best command for the job. The _count_ command is actually already available but we wont be properly making users aware of this command until we release version 0.5.

**Comment by Simon-Coetzee** [comment]
Hi again @TomSmithCGAT . So dedup looks like it's working now (The run time has increased a lot, but I assume that's because it's actually doing the dedup work now). The end of the log shows this
```
2017-06-04 16:56:33,462 INFO Input Reads: 69745906
2017-06-04 16:56:33,475 INFO Number of reads out: 16939780
# job finished in 79829 seconds at Sun Jun  4 16:56:33 2017 -- 79454.10 85.06  0.02  0.09 -- ac0b98f6-3b1f-487a-b333-7efb6b81c0cc
```
`group` is running currently and hasn't crashed, which is a good sign. I'm also trying `count` since, yes, your intuition was right that i was using this for umi counting. It's still running, but looking at the output file, it does not seem to be outputting gene names for me.
```
gene	count
	2
	934
	3
	3
	3
	3
	87
	3
	3
```
If i wanted to count "per cell" would you recommend that I split the fastq / bam into individual cells first, or do you have another method that you recommend?

**Comment by TomSmithCGAT** [comment]
We'll be supporting per-cell counting from a single BAM very soon! We should have a working version on a branch later this week if you wanted to test it out?

I'll have a look into that count output - not very useful having no gene names! 

That seems a long run time for 70M reads. I'm guessing this is because you have some genes with many UMIs which is making the network building stage very time consuming, The time taken to build the networks is quadratic with respect to the number of UMIs and linear with respect to their length. I'd therefore expect the de-duplication/counting will be much quicker when it's done at the cell level since the number of UMIs per cell per gene will be far fewer.

**Comment by TomSmithCGAT** [comment]
Hi @Simon-Coetzee. Are you OK if we close this issue now. I'll merge this branch into the master.
