### ISSUE TITLE
Error running setup.py

### ISSUE THREAD

**Issue by garrett-parker** [CGATOxford/UMI-tools#146]
Hi, I'm having trouble completing the install instructions. I want to be able to run umi_tools commands, but received this error following the install instructions.

[garrettp@n9923 UMI-tools-master]$ python setup.py install --user
Extracting in /tmp/tmpkEEr1r
Now working in /tmp/tmpkEEr1r/setuptools-10.0
Building a Setuptools egg in /u/home/g/garrettp/CSH_UMI-Tools/newTest/UMI-tools-master
Traceback (most recent call last):
  File "setup.py", line 217, in <module>
    dist = setuptools.setup(**setup_params)
  File "/usr/lib64/python2.6/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/usr/lib64/python2.6/distutils/dist.py", line 975, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python2.6/distutils/dist.py", line 995, in run_command
    cmd_obj.run()
  File "/work/tmp/tmpkEEr1r/setuptools-10.0/setuptools/command/bdist_egg.py", line 152, in run
    self.run_command("egg_info")
  File "/usr/lib64/python2.6/distutils/cmd.py", line 333, in run_command
    self.distribution.run_command(command)
  File "/usr/lib64/python2.6/distutils/dist.py", line 995, in run_command
    cmd_obj.run()
  File "/work/tmp/tmpkEEr1r/setuptools-10.0/setuptools/command/egg_info.py", line 179, in run
    self.find_sources()
  File "/work/tmp/tmpkEEr1r/setuptools-10.0/setuptools/command/egg_info.py", line 206, in find_sources
    mm.run()
  File "/work/tmp/tmpkEEr1r/setuptools-10.0/setuptools/command/egg_info.py", line 290, in run
    self.add_defaults()
  File "/work/tmp/tmpkEEr1r/setuptools-10.0/setuptools/command/egg_info.py", line 322, in add_defaults
    rcfiles = list(walk_revctrl())
  File "/work/tmp/tmpkEEr1r/setuptools-10.0/setuptools/command/sdist.py", line 18, in walk_revctrl
    for item in ep.load()(dirname):
  File "/work/tmp/tmpkEEr1r/setuptools-10.0/pkg_resources/__init__.py", line 2265, in load
    raise ImportError("%r has no %r attribute" % (entry, attr))
ImportError: <module 'setuptools.command.sdist' from '/work/tmp/tmpkEEr1r/setuptools-10.0/setuptools/command/sdist.py'> has no '_default_revctrl' attribute
/u/home/g/garrettp/CSH_UMI-Tools/newTest/UMI-tools-master/setuptools-10.0-py2.6.egg
Traceback (most recent call last):
  File "setup.py", line 6, in <module>
    use_setuptools("10.0")
  File "/u/home/g/garrettp/CSH_UMI-Tools/newTest/UMI-tools-master/ez_setup.py", line 178, in use_setuptools
    return _do_download(version, download_base, to_dir, download_delay)
  File "/u/home/g/garrettp/CSH_UMI-Tools/newTest/UMI-tools-master/ez_setup.py", line 129, in _do_download
    _build_egg(egg, archive, to_dir)
  File "/u/home/g/garrettp/CSH_UMI-Tools/newTest/UMI-tools-master/ez_setup.py", line 75, in _build_egg
    raise IOError('Could not build the egg.')
IOError: Could not build the egg.

**Comment by IanSudbery** [comment]
Hi Garret,

The real error is half way up that error stack:
 ```
ImportError: <module 'setuptools.command.sdist' from '/work/tmp/tmpkEEr1r/setuptools-10.0/setuptools/command/sdist.py'> has no '_default_revctrl' attribute
```

and is an error in installing or upgrading setuptools, which is a dependency of umi_tools. The minimum version of setuptools we require is 10.0 (the current version is 30-something). 

This issue:
https://github.com/pypa/setuptools/issues/320

Suggests it might be an incompatibility with the some Ubuntu versions. WHat OS are you running? Either way, the issue suggests updating setuptools to either the latest or at a minimum to 10.1 might solve the issue.

Are you able to such pip, easy_install or conda to do that?

With pip it would be 

```
pip install setuptools --upgrade
```

**Comment by garrett-parker** [comment]
Thanks, I have been receiving permission denied errors when I try to install setuptools. 
My OS is CentOS 6.9

pip returns
```
[garrettp@n9908 ~]$ pip install --upgrade setuptools --user
You are using pip version 6.0.8, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting setuptools from https://pypi.python.org/packages/e2/79/a865e78ab721a6dda2dea171526e6f8db51ba50814766429477e87c6ba8a/setuptools-36.2.0-py2.py3-none-any.whl#md5=6bff1e89b809a1efdb96929920e0bc12
  Using cached setuptools-36.2.0-py2.py3-none-any.whl
Installing collected packages: setuptools
  Found existing installation: distribute 0.6.10
    Uninstalling distribute-0.6.10:
      Exception:
      Traceback (most recent call last):
        File "/u/local/apps/python/2.6/lib/python2.6/site-packages/pip-6.0.8-py2.6.egg/pip/basecommand.py", line 232, in main
          status = self.run(options, args)
        File "/u/local/apps/python/2.6/lib/python2.6/site-packages/pip-6.0.8-py2.6.egg/pip/commands/install.py", line 347, in run
          root=options.root_path,
        File "/u/local/apps/python/2.6/lib/python2.6/site-packages/pip-6.0.8-py2.6.egg/pip/req/req_set.py", line 543, in install
          requirement.uninstall(auto_confirm=True)
        File "/u/local/apps/python/2.6/lib/python2.6/site-packages/pip-6.0.8-py2.6.egg/pip/req/req_install.py", line 667, in uninstall
          paths_to_remove.remove(auto_confirm)
        File "/u/local/apps/python/2.6/lib/python2.6/site-packages/pip-6.0.8-py2.6.egg/pip/req/req_uninstall.py", line 131, in remove
          self.dist.project_name, self.dist.version
        File "/usr/lib64/python2.6/contextlib.py", line 34, in __exit__
          self.gen.throw(type, value, traceback)
        File "/u/local/apps/python/2.6/lib/python2.6/site-packages/pip-6.0.8-py2.6.egg/pip/utils/logging.py", line 34, in indent_log
          yield
        File "/u/local/apps/python/2.6/lib/python2.6/site-packages/pip-6.0.8-py2.6.egg/pip/req/req_uninstall.py", line 126, in remove
          renames(path, new_path)
        File "/u/local/apps/python/2.6/lib/python2.6/site-packages/pip-6.0.8-py2.6.egg/pip/utils/__init__.py", line 316, in renames
          shutil.move(old, new)
        File "/usr/lib64/python2.6/shutil.py", line 261, in move
          os.unlink(src)
      OSError: [Errno 13] Permission denied: '/usr/bin/easy_install'
```

**Comment by garrett-parker** [comment]
I was able to solve this issue by loading python 2.7.13
```
module load python/2.7.13
```

Thank you, now my problem is that when I enter
```
[garrettp@n2191 UMI-tools]$ pip install umi_tools
Collecting umi_tools
  Downloading umi_tools-0.4.4.tar.gz (40kB)
    100% |████████████████████████████████| 40kB 193kB/s 
Requirement already satisfied: setuptools>=1.1 in /u/local/apps/python/2.7.13/lib/python2.7/site-packages (from umi_tools)
Requirement already satisfied: cython>=0.19 in /u/local/apps/python/2.7.13/lib/python2.7/site-packages (from umi_tools)
Requirement already satisfied: numpy>=1.7 in /u/local/apps/python/2.7.13/lib/python2.7/site-packages/numpy-1.12.1-py2.7-linux-x86_64.egg (from umi_tools)
Requirement already satisfied: pandas>=0.12.0 in /u/local/apps/python/2.7.13/lib/python2.7/site-packages (from umi_tools)
Requirement already satisfied: future in /u/local/apps/python/2.7.13/lib/python2.7/site-packages (from umi_tools)
Requirement already satisfied: six in /u/local/apps/python/2.7.13/lib/python2.7/site-packages (from umi_tools)
Requirement already satisfied: appdirs>=1.4.0 in /u/local/apps/python/2.7.13/lib/python2.7/site-packages (from setuptools>=1.1->umi_tools)
Requirement already satisfied: packaging>=16.8 in /u/local/apps/python/2.7.13/lib/python2.7/site-packages (from setuptools>=1.1->umi_tools)
Requirement already satisfied: pytz>=2011k in /u/local/apps/python/2.7.13/lib/python2.7/site-packages (from pandas>=0.12.0->umi_tools)
Requirement already satisfied: python-dateutil in /u/local/apps/python/2.7.13/lib/python2.7/site-packages (from pandas>=0.12.0->umi_tools)
Requirement already satisfied: pyparsing in /u/local/apps/python/2.7.13/lib/python2.7/site-packages (from packaging>=16.8->setuptools>=1.1->umi_tools)
Building wheels for collected packages: umi-tools
  Running setup.py bdist_wheel for umi-tools ... done
  Stored in directory: /u/home/g/garrettp/.cache/pip/wheels/c6/0f/d0/917ed151921dadbe8f6c7cbd9d3047388efc665eec7c155382
Successfully built umi-tools
Installing collected packages: umi-tools
Exception:
Traceback (most recent call last):
  File "/u/local/apps/python/2.7.13/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/u/local/apps/python/2.7.13/lib/python2.7/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/u/local/apps/python/2.7.13/lib/python2.7/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/u/local/apps/python/2.7.13/lib/python2.7/site-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/u/local/apps/python/2.7.13/lib/python2.7/site-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/u/local/apps/python/2.7.13/lib/python2.7/site-packages/pip/wheel.py", line 345, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/u/local/apps/python/2.7.13/lib/python2.7/site-packages/pip/wheel.py", line 316, in clobber
    ensure_dir(destdir)
  File "/u/local/apps/python/2.7.13/lib/python2.7/site-packages/pip/utils/__init__.py", line 83, in ensure_dir
    os.makedirs(path)
  File "/u/local/apps/python/2.7.13/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/u/local/apps/python/2.7.13/lib/python2.7/site-packages/umi_tools'

```

**Comment by IanSudbery** [comment]
Looks like you don't have the correct permissions to write to your local library. Have you tried with `--user` on the `pip install umi_tools`?

**Comment by garrett-parker** [comment]
Thanks. I successfully installed umi_tools. However,
```
$ umi_tools dedup -I example.bam --output-stats=deduplicated -S deduplicated.bam
-bash: umi_tools: command not found
```
isn't working.

**Comment by IanSudbery** [comment]
I'm assume you got this working?

**Comment by garrett-parker** [comment]
Not quite. I closed it because I succeeded in installing umi_tools. However, the umi_tools commands aren't working.

```
$ umi_tools extract --stdin=example.fastq.gz --bc-pattern=NNNNNNNNN --log=processed.log --stdout processed.fastq.gz 
```
returns
```
-bash: umi_tools: command not found
```

**Comment by IanSudbery** [comment]
You did loaded a different version of python in to do the installation right?
Have you made sure this is active before you call umi_tools?

**Comment by garrett-parker** [comment]
which python returns
```
[garrettp@login1 ~]$ which python
alias python='/u/home/s/serghei/anaconda2/bin/python'
	/u/home/s/serghei/anaconda2/bin/python

```

**Comment by IanSudbery** [comment]
Is this the python you were using when you installed? Have you done 

```
module load python/2.7.13
```
in this session? 


The other thing to check is your path

```
pip install --user
```
should install binaries to `~/.local/bin`. This is automatically on your `$PATH` in more recent linux versions, but not older ones. 

Can you check if `umi_tools` is listed when you do `ls ~/.local/bin` and if `~/.local/bin` is listed when you do `echo $PATH`?

**Comment by garrett-parker** [comment]
Yes this is the python I used to successfully install.

I was able to solve my issue by changing the PATH with 
```
$ export PATH=$PATH:~/.local/bin
```

Thank you!
