### ISSUE TITLE
Paired-end grouped BAM output fails

### ISSUE THREAD

**Issue by koelling** [CGATOxford/UMI-tools#149]
I'm getting the following error using the latest umi_tools with Python 3.6:

```
 output generated by group --log2stderr --method directional --paired --output-bam -I analysis/bam/SampleB_S2.bam -S analysis/umi_group/SampleB_S2.unsorted.bam
# pid: XXX, system: Linux 2.6.32-642.6.2.el6.x86_64 #1 SMP Wed Oct 26 06:52:09 UTC 2016 x86_64
# chrom                                   : None
# gene_tag                                : None
# gene_transcript_map                     : None
# get_umi_method                          : read_id
# in_sam                                  : False
# log2stderr                              : True
# loglevel                                : 1
# mapping_quality                         : 0
# method                                  : directional
# out_sam                                 : False
# output_bam                              : True
# output_unmapped                         : False
# paired                                  : True
# per_contig                              : False
# per_gene                                : False
# random_seed                             : None
# read_length                             : False
# short_help                              : None
# soft                                    : 4
# spliced                                 : False
# stderr                                  : <_io.TextIOWrapper name='<stderr>' mode='w' encoding='UTF-8'>
# stdin                                   : <_io.TextIOWrapper name='analysis/bam/SampleB_S2.bam' mode='r' encoding='UTF-8'>
# stdlog                                  : <_io.TextIOWrapper name='<stderr>' mode='w' encoding='UTF-8'>
# stdout                                  : <_io.TextIOWrapper name='analysis/umi_group/SampleB_S2.unsorted.bam' mode='w' encoding='UTF-8'>
# subset                                  : None
# threshold                               : 1
# timeit_file                             : None
# timeit_header                           : None
# timeit_name                             : all
# tsv                                     : None
# umi_group_tag                           : BX
# umi_sep                                 : _
# umi_tag                                 : RX
# whole_contig                            : False
Traceback (most recent call last):
  File "XXX/anaconda3/bin/umi_tools", line 11, in <module>
    sys.exit(main())
  File "XXX/anaconda3/lib/python3.6/site-packages/umi_tools/umi_tools.py", line 46, in main
    module.main(sys.argv)
  File "XXX/anaconda3/lib/python3.6/site-packages/umi_tools/group.py", line 520, in main
    outfile.write(read, unique_id, top_umi)
TypeError: write() takes exactly one argument (3 given)
```

**Comment by koelling** [comment]
Just saw this has already been reported as #132
