### ISSUE TITLE
problem in running UMI-tools quick start guide

### ISSUE THREAD

**Issue by J-sara** [CGATOxford/UMI-tools#169]
Hello,

I am tring to follow the provided commands in the tutorial but when I run the  `umi_tools dedup -I example.bam --output-stats=deduplicated -S deduplicated.bam` command I get the following error:

`Traceback (most recent call last):
  File "/home/ehsan/anaconda2/bin/umi_tools", line 11, in <module>
    load_entry_point('umi-tools==0.5.0', 'console_scripts', 'umi_tools')()
  File "/home/ehsan/anaconda2/lib/python2.7/site-packages/umi_tools-0.5.0-py2.7-linux-x86_64.egg/umi_tools/umi_tools.py", line 50, in main
    module.main(sys.argv)
  File "/home/ehsan/anaconda2/lib/python2.7/site-packages/umi_tools-0.5.0-py2.7-linux-x86_64.egg/umi_tools/dedup.py", line 220, in main
    inreads = infile.fetch()
  File "pysam/libcalignmentfile.pyx", line 869, in pysam.libcalignmentfile.AlignmentFile.fetch (pysam/libcalignmentfile.c:11392)
ValueError: fetch called on bamfile without index
`

Could you please tell me how to solve this error?

Best

**Comment by IanSudbery** [comment]
Hi,

UMI-tools requires that the imput file is indexed.

i.e.

```
$ samtools index example.bam
```

See note at top of the QUICK_START page.
