### ISSUE TITLE
whitelist --expect-cells: ERROR No local minima was accepted

### ISSUE THREAD

**Issue by romanhaa** [CGATOxford/UMI-tools#215]
Hi guys,

When using the `--expect-cells option=2000` in the whitelist command I always receive an error as shown below

```
2017-11-28 14:22:47,206 INFO Parsed 55000000 reads
2017-11-28 14:22:49,395 INFO Parsed 55100000 reads
2017-11-28 14:22:51,585 INFO Parsed 55200000 reads
2017-11-28 14:22:53,785 INFO Parsed 55300000 reads
2017-11-28 14:22:55,982 INFO Parsed 55400000 reads
2017-11-28 14:22:58,182 INFO Parsed 55500000 reads
2017-11-28 14:23:00,374 INFO Parsed 55600000 reads
2017-11-28 14:23:02,576 INFO Parsed 55700000 reads
2017-11-28 14:23:03,557 INFO Starting - whitelist determination
2017-11-28 14:24:53,505 INFO Finished - whitelist determination
2017-11-28 14:24:53,506 ERROR No local minima was accepted. Recommend checking the plot output and counts per local minima (requires --plot-prefix option) and then re-running with manually selected threshold (--set-cell-number option)
Traceback (most recent call last):
File "/data/PGP/rhillje/tools/miniconda2/envs/rhillje/bin/umi_tools", line 11, in <module> sys.exit(main())
File "/data/PGP/rhillje/tools/miniconda2/envs/rhillje/lib/python2.7/site-packages/umi_tools/umi_tools.py", line 59, in main module.main(sys.argv)
File "/data/PGP/rhillje/tools/miniconda2/envs/rhillje/lib/python2.7/site-packages/umi_tools/whitelist.py", line 371, in main options.plot_prefix)
File "/data/PGP/rhillje/tools/miniconda2/envs/rhillje/lib/python2.7/site-packages/umi_tools/umi_methods.py", line 405, in getCellWhitelist U.error("No local minima was accepted. Recommend checking the plot "
File "/data/PGP/rhillje/tools/miniconda2/envs/rhillje/lib/python2.7/site-packages/umi_tools/Utilities.py", line 1097, in error raise ValueError("UMI-tools failed with an error. Check the log file")
ValueError: UMI-tools failed with an error. Check the log file
```

However, when I replace it with `--set-cell-number=2500` it works without issues.

Anybody an idea what the issue could be?

EDIT:

Thought it might make sense to add the original command that I ran:

```
umi_tools whitelist --stdin sample1_R1.fastq.gz \
                    --extract-method=string \
                    --bc-pattern=CCCCCCCCCCCCCCCCNNNNNNNNNN \
                    --expect-cells=2000 \
                    --error-correct-threshold=1 \
                    --plot-prefix=sample1_R1 \
                    --method=reads \
                    --log2stderr > whitelist_reads_expect_2000.txt
```

For reference, the error occurs also when changing `--method` to `umis`.

**Comment by TomSmithCGAT** [comment]
Hi @romanhaa. Unfortunately the process of selecting the threshold requires some heuristic filters which can sometimes lead to the correct threshold being missed and hence the error message. These filters are partially based on the expected number of cells which I suspect is why the error only occurs with  `--expect-cells option=2000`. Could you post the plots and table with the  `sample1_R1` prefix so we can try and diagnose this further

**Comment by romanhaa** [comment]
Thanks for the reply. I uploaded the plots here: https://imgur.com/a/tOKYm

The content of the table is the following:

```
count	action
2554	Rejected
3025	Rejected
```

Based on this information I decided to use 2500 as a manual threshold.

Is that all the information you need? Let me know if you need anything else.

**Comment by TomSmithCGAT** [comment]
Thanks @romanhaa - Yes I think a threshold of 2500 in your case looks appropriate. From an inspection of the plots, I can't see why this was rejected but I'll take another look at the thresholds to see what might be going on here.

**Comment by romanhaa** [comment]
Thanks a lot @TomSmithCGAT - I'll use this as a workaround for now and hope that we can figure out what's the problem.

**Comment by romanhaa** [comment]
I just noticed that for another sample the `--expect-cells` command ran fine. We expected a similar cell count in all of our four samples but already found through the original 10x pipeline that something must've gone wrong (experimentally) with this particular sample because the cell count is much lower (~650 as compared to ~2000). I was wondering if perhaps the `--expect-cells` fails if I enter a number that is lower than the one estimated by the algorithm? I think it's rather unlikely but from my limited set of four samples this would fit.

Here are the images and the content of the `tsv` file: https://imgur.com/a/eEXz0

```
count	action
644	Selected
703	Rejected
```

I'll run it again with the `--expect-cells` on the other samples with a higher expected cell number to see if this helps.

**Comment by TomSmithCGAT** [comment]
@romanhaa and anyone else reading this issue, from version `1.0.0` onwards, the knee method has been updated and should now be more stable. We are interested in all feedback for the updated method. Please post a new issue if you have found the new method works better, or indeed if you are still having issues.

**Comment by gwangjinkim** [comment]
@romanhaa and all other people encountering this issue: try to enhance your `--expect-cells` value, then it might find a higher value. Maybe one should write into the instructions that one should give there a number greater than the expected cells. We had a case where it worked with 4000 cells but not with 3000 cells. The accepted number was 3043. So the `--expect-cells` value must be greater than the estimated number, otherwise this error will occur!

**Comment by romanhaa** [comment]
I'm pretty sure that's actually written somewhere already. The possible detected thresholds can be between 10% and 100% of the value in `--expect-cells`.
