### ISSUE TITLE
Running Whitelist and getting IndexError: list index out of range

### ISSUE THREAD

**Issue by tom-snir** [CGATOxford/UMI-tools#235]
I am running the following command:

>[tom@zelda Melanoma]$ umi_tools whitelist --stdin InvMelanoma_S4_L001_R1_001.fastq \
>                     --extract-method=regex \
>                     --bc-pattern="(?P<cell_1>.{8,12})(?P<discard_1>GAGTGATTGCTTGTGACGCCTT){s<=2}(?P<cell_2>.{8})(?P<umi_1>.{6})T{3}.*" \
>                     --expect-cells=300 \
>                     --plot-prefix=expect_whitelist \
>                     --log2stderr > whitelist.txt

output generated by whitelist --stdin InvMelanoma_S4_L001_R1_001.fastq --extract-method=regex --bc-pattern=(?P<cell_1>.{8,12})(?P<discard_1>GAGTGATTGCTTGTGACGCCTT){s<=2}(?P<cell_2>.{8})(?P<umi_1>.{6})T{3}.* --expect-cells=300 --plot-prefix=expect_whitelist --log2stderr
job started at Thu Feb 15 13:44:07 2018 on zelda -- a207a0d7-d0db-429e-8a35-d0816f61ee22
pid: 78695, system: Linux 2.6.32-696.6.3.el6.x86_64 #1 SMP Wed Jul 12 14:17:22 UTC 2017 x86_64
blacklist_tsv                           : None
cell_number                             : False
compresslevel                           : 6
error_correct_threshold                 : 1
expect_cells                            : 300
extract_method                          : regex
filter_cell_barcodes                    : False
log2stderr                              : True
loglevel                                : 1
method                                  : reads
pattern                                 : (?P<cell_1>.{8,12})(?P<discard_1>GAGTGATTGCTTGTGACGCCTT){s<=2}(?P<cell_2>.{8})(?P<umi_1>.{6})T{3}.*
pattern2                                : None
plot_prefix                             : expect_whitelist
prime3                                  : None
random_seed                             : None
read2_in                                : None
short_help                              : None
stderr                                  : <open file '<stderr>', mode 'w' at 0x7f8523b601e0>
stdin                                   : <open file 'InvMelanoma_S4_L001_R1_001.fastq', mode 'r' at 0x7f851ab5c150>
stdlog                                  : <open file '<stderr>', mode 'w' at 0x7f8523b601e0>
stdout                                  : <open file '<stdout>', mode 'w' at 0x7f8523b60150>
subset_reads                            : 100000000
timeit_file                             : None
timeit_header                           : None
timeit_name                             : all
whitelist_tsv                           : None

And I get the following output, ending with an error:

2018-02-15 13:44:07,518 INFO Starting barcode extraction
2018-02-15 13:44:07,518 INFO Parsed 0 reads
2018-02-15 13:44:08,090 INFO Parsed 100000 reads
2018-02-15 13:44:08,658 INFO Parsed 200000 reads
2018-02-15 13:44:09,226 INFO Parsed 300000 reads
2018-02-15 13:44:09,796 INFO Parsed 400000 reads
2018-02-15 13:44:10,362 INFO Parsed 500000 reads
2018-02-15 13:44:10,931 INFO Parsed 600000 reads
2018-02-15 13:44:11,500 INFO Parsed 700000 reads
2018-02-15 13:44:12,069 INFO Parsed 800000 reads
2018-02-15 13:44:12,638 INFO Parsed 900000 reads
2018-02-15 13:44:13,205 INFO Parsed 1000000 reads
2018-02-15 13:44:13,773 INFO Parsed 1100000 reads
2018-02-15 13:44:14,342 INFO Parsed 1200000 reads
2018-02-15 13:44:14,911 INFO Parsed 1300000 reads
2018-02-15 13:44:15,479 INFO Parsed 1400000 reads
2018-02-15 13:44:16,046 INFO Parsed 1500000 reads
2018-02-15 13:44:16,614 INFO Parsed 1600000 reads
2018-02-15 13:44:17,181 INFO Parsed 1700000 reads
2018-02-15 13:44:17,748 INFO Parsed 1800000 reads
2018-02-15 13:44:18,315 INFO Parsed 1900000 reads
2018-02-15 13:44:18,884 INFO Parsed 2000000 reads
2018-02-15 13:44:19,453 INFO Parsed 2100000 reads
2018-02-15 13:44:20,022 INFO Parsed 2200000 reads
2018-02-15 13:44:20,593 INFO Parsed 2300000 reads
2018-02-15 13:44:21,161 INFO Parsed 2400000 reads
2018-02-15 13:44:21,732 INFO Parsed 2500000 reads
2018-02-15 13:44:22,301 INFO Parsed 2600000 reads
2018-02-15 13:44:22,870 INFO Parsed 2700000 reads
2018-02-15 13:44:23,437 INFO Parsed 2800000 reads
2018-02-15 13:44:24,007 INFO Parsed 2900000 reads
2018-02-15 13:44:24,575 INFO Parsed 3000000 reads
2018-02-15 13:44:25,145 INFO Parsed 3100000 reads
2018-02-15 13:44:25,714 INFO Parsed 3200000 reads
2018-02-15 13:44:26,283 INFO Parsed 3300000 reads
2018-02-15 13:44:26,851 INFO Parsed 3400000 reads
2018-02-15 13:44:27,420 INFO Parsed 3500000 reads
2018-02-15 13:44:27,989 INFO Parsed 3600000 reads
2018-02-15 13:44:28,558 INFO Parsed 3700000 reads
2018-02-15 13:44:29,127 INFO Parsed 3800000 reads
2018-02-15 13:44:29,695 INFO Parsed 3900000 reads
2018-02-15 13:44:30,263 INFO Parsed 4000000 reads
2018-02-15 13:44:30,832 INFO Parsed 4100000 reads
2018-02-15 13:44:31,399 INFO Parsed 4200000 reads
2018-02-15 13:44:31,969 INFO Parsed 4300000 reads
2018-02-15 13:44:32,539 INFO Parsed 4400000 reads
2018-02-15 13:44:33,107 INFO Parsed 4500000 reads
2018-02-15 13:44:33,676 INFO Parsed 4600000 reads
2018-02-15 13:44:34,246 INFO Parsed 4700000 reads
2018-02-15 13:44:34,814 INFO Parsed 4800000 reads
2018-02-15 13:44:35,382 INFO Parsed 4900000 reads
2018-02-15 13:44:35,950 INFO Parsed 5000000 reads
2018-02-15 13:44:36,518 INFO Parsed 5100000 reads
2018-02-15 13:44:37,086 INFO Parsed 5200000 reads
2018-02-15 13:44:37,654 INFO Parsed 5300000 reads
2018-02-15 13:44:38,221 INFO Parsed 5400000 reads
2018-02-15 13:44:38,790 INFO Parsed 5500000 reads
2018-02-15 13:44:39,358 INFO Parsed 5600000 reads
2018-02-15 13:44:39,928 INFO Parsed 5700000 reads
2018-02-15 13:44:40,498 INFO Parsed 5800000 reads
2018-02-15 13:44:41,066 INFO Parsed 5900000 reads
2018-02-15 13:44:41,634 INFO Parsed 6000000 reads
2018-02-15 13:44:42,205 INFO Parsed 6100000 reads
2018-02-15 13:44:42,773 INFO Parsed 6200000 reads
2018-02-15 13:44:43,345 INFO Parsed 6300000 reads
2018-02-15 13:44:43,916 INFO Parsed 6400000 reads
2018-02-15 13:44:44,485 INFO Parsed 6500000 reads
2018-02-15 13:44:45,054 INFO Parsed 6600000 reads
2018-02-15 13:44:45,623 INFO Parsed 6700000 reads
2018-02-15 13:44:46,192 INFO Parsed 6800000 reads
2018-02-15 13:44:46,761 INFO Parsed 6900000 reads
2018-02-15 13:44:47,330 INFO Parsed 7000000 reads
2018-02-15 13:44:47,898 INFO Parsed 7100000 reads
2018-02-15 13:44:48,466 INFO Parsed 7200000 reads
2018-02-15 13:44:49,035 INFO Parsed 7300000 reads
2018-02-15 13:44:49,604 INFO Parsed 7400000 reads
2018-02-15 13:44:50,173 INFO Parsed 7500000 reads
2018-02-15 13:44:50,743 INFO Parsed 7600000 reads
2018-02-15 13:44:51,312 INFO Parsed 7700000 reads
2018-02-15 13:44:51,882 INFO Parsed 7800000 reads
2018-02-15 13:44:52,450 INFO Parsed 7900000 reads
2018-02-15 13:44:53,018 INFO Parsed 8000000 reads
2018-02-15 13:44:53,587 INFO Parsed 8100000 reads
2018-02-15 13:44:54,155 INFO Parsed 8200000 reads
2018-02-15 13:44:54,728 INFO Parsed 8300000 reads
2018-02-15 13:44:55,297 INFO Parsed 8400000 reads
2018-02-15 13:44:55,864 INFO Parsed 8500000 reads
2018-02-15 13:44:56,432 INFO Parsed 8600000 reads
2018-02-15 13:44:57,001 INFO Parsed 8700000 reads
2018-02-15 13:44:57,572 INFO Parsed 8800000 reads
2018-02-15 13:44:58,143 INFO Parsed 8900000 reads
2018-02-15 13:44:58,712 INFO Parsed 9000000 reads
2018-02-15 13:44:59,281 INFO Parsed 9100000 reads
2018-02-15 13:44:59,848 INFO Parsed 9200000 reads
2018-02-15 13:45:00,417 INFO Parsed 9300000 reads
2018-02-15 13:45:00,987 INFO Parsed 9400000 reads
2018-02-15 13:45:01,555 INFO Parsed 9500000 reads
2018-02-15 13:45:02,124 INFO Parsed 9600000 reads
2018-02-15 13:45:02,693 INFO Parsed 9700000 reads
2018-02-15 13:45:03,263 INFO Parsed 9800000 reads
2018-02-15 13:45:03,829 INFO Parsed 9900000 reads
2018-02-15 13:45:04,399 INFO Parsed 10000000 reads
2018-02-15 13:45:04,967 INFO Parsed 10100000 reads
2018-02-15 13:45:05,537 INFO Parsed 10200000 reads
2018-02-15 13:45:06,106 INFO Parsed 10300000 reads
2018-02-15 13:45:06,676 INFO Parsed 10400000 reads
2018-02-15 13:45:06,910 INFO Starting - whitelist determination
Traceback (most recent call last):
  File "/usr/local/bin/umi_tools", line 11, in <module>
    load_entry_point('umi-tools==0.5.3', 'console_scripts', 'umi_tools')()
  File "/usr/local/lib/python2.7/site-packages/umi_tools-0.5.3-py2.7-linux-x86_64.egg/umi_tools/umi_tools.py", line 59, in main
    module.main(sys.argv)
  File "/usr/local/lib/python2.7/site-packages/umi_tools-0.5.3-py2.7-linux-x86_64.egg/umi_tools/whitelist.py", line 371, in main
    options.plot_prefix)
  File "/usr/local/lib/python2.7/site-packages/umi_tools-0.5.3-py2.7-linux-x86_64.egg/umi_tools/umi_methods.py", line 400, in getCellWhitelist
    cell_barcode_counts, expect_cells, cell_number, plotfile_prefix)
  File "/usr/local/lib/python2.7/site-packages/umi_tools-0.5.3-py2.7-linux-x86_64.egg/umi_tools/umi_methods.py", line 160, in getKneeEstimate
    threshold = 0.001 * cell_barcode_counts.most_common(1)[0][1]
IndexError: list index out of range

Any idea what the problem is?

**Comment by tom-snir** [comment]
Anyone experienced something similar? Looking for any advice regarding this issue.

Thank you!

**Comment by zionjeong** [comment]
Hello, 
I have an exactly same issue :,(
Is anybody can help me? Thanks.

**Comment by IanSudbery** [comment]
@TomSmithCGAT I guess this is a problem with failing to find a suitable knee estimate?

**Comment by TomSmithCGAT** [comment]
Hi all. Sorry for not picking up on this sooner. The error seems to stem from the cell barcode counter being empty, which would only occur if the pattern used to extract the cell barcodes is not suitable. 

@IanSudbery  - This error occurs before any attempt to actually find the knee. For the next update we should include a sanity check that we the cell barcode counts are non-zero at this point

@tom-snir & @zionjeong - Would you mind posting an explanation of where you expect the cell barcodes to reside in the read(s) and the command use in `umi_tools whitelist`. Could you also please run `umi_tools extract` on a subset of say 1M reads, using the same patterns and check that the cell barcodes can be correctly extracted.

**Comment by zionjeong** [comment]
Thank you for the prompt reply on the issue.
 I just found an error in 'bc-pattern' and solved the problem. Actually, I am working on illumina-biorad ddSeq platform using Surecell scRNA-Seq library kit. The barcode and UMI structures in read1 are completely different with other systems so I made a mistake in the bc-pattern description. For someone who have interested in, I used,
--bc-pattern="(?P<cell_1>.{6})(?P<discard_1>TAGCCATCGCATTGC)(?P<cell_2>.{6})(?P<discard_2>TACCTCTGAGCTGAA)(?P<cell_3>.{6})(?P<discard_3>ACG)(?P<umi_1>.{8}).*"

Thanks for the great tools :)

**Comment by TomSmithCGAT** [comment]
Ah great. Glad to hear you've solved it. Hopefully @tom-snir's issue will be similar

**Comment by TomSmithCGAT** [comment]
I'm closing this issue due to low activity
