### ISSUE TITLE
umi_tools dedup MemoryError

### ISSUE THREAD

**Issue by srialle** [CGATOxford/UMI-tools#246]
Dear developpers,

First, thank you very much for developping this useful tool. I have run UMI-tools dedup on 10 amplicon samples previously processed with umi_tools extract. For 4 samples (the ones with the more UMI counts), I get a Memory Error. I run the tool on a server with 128Go RAM.

Here is an example of the log file for one of the samples which generates the error:
```
# output generated by dedup -I H1.aligned.sort.bam --output-stats=H1.dedup.txt -S H1.dedup.bam
# job started at Tue Mar 20 16:39:13 2018 on agrios -- 59a30bfb-f092-4fbe-bf36-822d9c1bf84b
# pid: 29069, system: Linux 3.10.0-514.26.2.el7.x86_64 #1 SMP Tue Jul 4 15:04:05 UTC 2017 x86_64
# cell_tag                                : None
# cell_tag_delim                          : None
# cell_tag_split                          : -
# chrom                                   : None
# compresslevel                           : 6
# detection_method                        : None
# gene_tag                                : None
# gene_transcript_map                     : None
# get_umi_method                          : read_id
# ignore_umi                              : False
# in_sam                                  : False
# log2stderr                              : False
# loglevel                                : 1
# mapping_quality                         : 0
# method                                  : directional
# no_sort_output                          : False
# out_sam                                 : False
# paired                                  : False
# per_cell                                : False
# per_contig                              : False
# per_gene                                : False
# random_seed                             : None
# read_length                             : False
# short_help                              : None
# skip_regex                              : ^[__|Unassigned]
# soft_clip_threshold                     : 4
# spliced                                 : False
# stats                                   : H1.dedup.txt
# stderr                                  : <open file '<stderr>', mode 'w' at 0x7fb675ffa1e0>
# stdin                                   : <open file 'H1.aligned.sort.bam', mode 'r' at 0x7fb63e872db0>
# stdlog                                  : <open file '<stdout>', mode 'w' at 0x7fb675ffa150>
# stdout                                  : <open file 'H1.dedup.bam', mode 'w' at 0x7fb63e872c90>
# subset                                  : None
# threshold                               : 1
# timeit_file                             : None
# timeit_header                           : None
# timeit_name                             : all
# umi_sep                                 : _
# umi_tag                                 : RX
# umi_tag_delim                           : None
# umi_tag_split                           : None
# whole_contig                            : False
2018-03-20 16:39:15,803 INFO total_umis 428875
2018-03-20 16:39:15,804 INFO #umis 254627
Traceback (most recent call last):
  File "/home/srialle/miniconda2/bin/umi_tools", line 11, in <module>
    sys.exit(main())
  File "/home/srialle/miniconda2/lib/python2.7/site-packages/umi_tools/umi_tools.py", line 59, in main
    module.main(sys.argv)
  File "/home/srialle/miniconda2/lib/python2.7/site-packages/umi_tools/dedup.py", line 259, in main
    average_distance = umi_methods.get_average_umi_distance(bundle.keys())
  File "/home/srialle/miniconda2/lib/python2.7/site-packages/umi_tools/umi_methods.py", line 550, in get_average_umi_distance
    x, y in itertools.combinations(umis, 2)]
MemoryError
```
The max \#umis that doesn't lead to en error in my samples is 209546.

Any idea on how to solve the problem?

Thanks,

Stephanie

**Comment by IanSudbery** [comment]
Hi Stephanie,

You'll use less memory and do things quicker if you out don't output stats.

 However, how long are your UMIs? With a 10bp UMI there are approximately 1M possible distinct UMIs. With 0.25M distinct UMIs the networks are likely to become so dense that it does become time and memory intensive to disentangle them. In addition, UMI tools relies to a certain extent on the assumption that two UMIs that differ at only a single base are more likely to have arisen due to an error than to be genuinely different molecules. At high UMI depths this assumption is questionable. The directional method (as opposed to say cluster or adjacency) mitigates against this to a certain extent, but there is only so much it can do. 

My advice is to remove the --output-stats, but I think its probably still going to take a long time and use a lot of memory.  Its possible you will also over-collapse.
