### ISSUE TITLE
Error after installing with conda

### ISSUE THREAD

**Issue by taylorreiter** [CGATOxford/UMI-tools#292]
Hi All,

I installed UMI-tools with the command:
```
conda install umi_tools
```
When running
```
umi_tools extract --stdin=BMANA4_S135_L007_R1_001.fastq.gz --bc-pattern NNNNNXXXX
```

I received the following error:
```
Traceback (most recent call last):
  File "/Users/taylorreiter/miniconda3/envs/pn/bin/umi_tools", line 11, in <module>
    sys.exit(main())
  File "/Users/taylorreiter/miniconda3/envs/pn/lib/python3.6/site-packages/umi_tools/umi_tools.py", line 56, in main
    module = imp.load_module(command, file, pathname, description)
  File "/Users/taylorreiter/miniconda3/envs/pn/lib/python3.6/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/Users/taylorreiter/miniconda3/envs/pn/lib/python3.6/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 675, in _load
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/Users/taylorreiter/miniconda3/envs/pn/lib/python3.6/site-packages/umi_tools/extract.py", line 78, in <module>
    import regex
  File "/Users/taylorreiter/miniconda3/envs/pn/lib/python3.6/site-packages/regex.py", line 394, in <module>
    import _regex_core
  File "/Users/taylorreiter/miniconda3/envs/pn/lib/python3.6/site-packages/_regex_core.py", line 21, in <module>
    import _regex
ImportError: dlopen(/Users/taylorreiter/miniconda3/envs/pn/lib/python3.6/site-packages/_regex.cpython-36m-darwin.so, 2): Symbol not found: _PySlice_AdjustIndices
  Referenced from: /Users/taylorreiter/miniconda3/envs/pn/lib/python3.6/site-packages/_regex.cpython-36m-darwin.so
  Expected in: flat namespace
 in /Users/taylorreiter/miniconda3/envs/pn/lib/python3.6/site-packages/_regex.cpython-36m-darwin.so
```
Upon upgrading from python 3.6.0 to python 3.6.1, the error was resolved.

**Comment by IanSudbery** [comment]
@TomSmithCGAT Which python version does the py3 testing suite use?

**Comment by TomSmithCGAT** [comment]
python 3.5 (https://github.com/CGATOxford/UMI-tools/blob/master/.travis.yml)

**Comment by TomSmithCGAT** [comment]
Thanks for letting us know about this apparent python version specific @taylorreiter. We'll keep an eye out for any similar issues.
