### ISSUE TITLE
Error on single-end sam file

### ISSUE THREAD

**Issue by mandiedriskill** [CGATOxford/UMI-tools#294]
Hello,

I am try to run umi_tools dedupe, but I am running into the following error:
Traceback (most recent call last):

  File "/Users/mandiedriskill/miniconda3/bin/umi_tools", line 11, in <module>
    sys.exit(main())
  File "/Users/mandiedriskill/miniconda3/lib/python3.6/site-packages/umi_tools/umi_tools.py", line 59, in main
    module.main(sys.argv)
  File "/Users/mandiedriskill/miniconda3/lib/python3.6/site-packages/umi_tools/dedup.py", line 146, in main
    raise ValueError("Input on standard in not currently supported")
ValueError: Input on standard in not currently supported

This is the code and flags I am using:
umi_tools dedup --in-sam /Users/mandiedriskill/Desktop/Barkan_Project/view_cp_genome_102617_Total-15Dark_Rep1_mergedAligned.out.sam --out-sam new_test.bam --umi-separator=:

The sam file is sorted, but not indexed. 
Any help would be appreciate. Thanks

**Comment by mandiedriskill** [comment]
I figured this problem out by indexing the bam.
