### ISSUE TITLE
pysam error while running umi_tools dedup

### ISSUE THREAD

**Issue by geocarvalho** [CGATOxford/UMI-tools#295]
Hello, thank you for the UMI-tools, this week I'm in trouble with the pysam.
When I run the `umi_tools dedup` command I receive the error bellow

```
$ umi_tools dedup -I /path/to/sample/tmp/sample.sorted.bam --paired -S /path/to/sample/tmp/sample.dedup.bam
# output generated by dedup -I /path/to/sample/tmp/sample.sorted.bam --paired -S /path/to/sample/tmp/sample.dedup.bam
# job started at Tue Nov  6 15:48:08 2018 on 06e6d0eb07dd -- 62759ec6-adbf-475d-96a5-b19817261cdd
# pid: 103443, system: Linux 4.4.0-87-generic #110-Ubuntu SMP Tue Jul 18 12:55:35 UTC 2017 x86_64
# cell_tag                                : None
# cell_tag_delim                          : None
# cell_tag_split                          : -
# chrom                                   : None
# compresslevel                           : 6
# detection_method                        : None
# gene_tag                                : None
# gene_transcript_map                     : None
# get_umi_method                          : read_id
# ignore_umi                              : False
# in_sam                                  : False
# log2stderr                              : False
# loglevel                                : 1
# mapping_quality                         : 0
# method                                  : directional
# no_sort_output                          : False
# out_sam                                 : False
# paired                                  : True
# per_cell                                : False
# per_contig                              : False
# per_gene                                : False
# random_seed                             : None
# read_length                             : False
# short_help                              : None
# skip_regex                              : ^(__|Unassigned)
# soft_clip_threshold                     : 4
# spliced                                 : False
# stats                                   : False
# stderr                                  : <open file '<stderr>', mode 'w' at 0x7f5fd00ae1e0>
# stdin                                   : <open file '/path/to/sample/tmp/sample.sorted.bam', mode 'r' at 0x7f5faf303390>
# stdlog                                  : <open file '<stdout>', mode 'w' at 0x7f5fd00ae150>
# stdout                                  : <open file '/path/to/sample/tmp/sample.dedup.bam', mode 'w' at 0x7f5faf303660>
# subset                                  : None
# threshold                               : 1
# timeit_file                             : None
# timeit_header                           : None
# timeit_name                             : all
# umi_sep                                 : _
# umi_tag                                 : RX
# umi_tag_delim                           : None
# umi_tag_split                           : None
# whole_contig                            : False
2018-11-06 15:48:24,905 INFO Written out 100000 reads
2018-11-06 15:48:26,348 INFO Searching for mates for 311 unmatched alignments
2018-11-06 15:48:28,198 INFO 0 mates never found
Traceback (most recent call last):
  File "/usr/local/anaconda/envs/cnv_env/bin/umi_tools", line 11, in <module>
    sys.exit(main())
  File "/usr/local/anaconda/envs/cnv_env/lib/python2.7/site-packages/umi_tools/umi_tools.py", line 59, in main
    module.main(sys.argv)
  File "/usr/local/anaconda/envs/cnv_env/lib/python2.7/site-packages/umi_tools/dedup.py", line 306, in main
    pysam.sort("-o", sorted_out_name, "-O", sort_format, out_name)
  File "/usr/local/anaconda/envs/cnv_env/lib/python2.7/site-packages/pysam/__init__.py", line 79, in __call__
    (retval, "\n".join(stderr)))
pysam.SamtoolsError: 'csamtools returned with error 1: [bam_sort] no prefix specified for temporary files (use -T option)\n'
```
When I updated the pysam 0.8.4 to 0.15.1 it worked.

**Comment by TomSmithCGAT** [comment]
Thanks for making us aware of this @geocarvalho. From a quick scan of the `pysam` and `samtools` release notes, it looks like our dependency should be `pysam > 0.9` which is where the switch to `htslib: 1.3.1` occurred, after which the `samtools sort` usage changed. I'll update our requirements
