### ISSUE TITLE
Python 3.7: `imp` needs byte-like object

### ISSUE THREAD

**Issue by rekado** [CGATOxford/UMI-tools#318]
Hi,

with umi-tools 0.5.5 built with Python 3.7 I get this error when printing the help for any sub-command:

~~~
rekado in master: /gnu/store/h5w9i2x61gv36j4hyqwwjj7b5rq5pg6b-umi-tools-0.5.5/bin/umi_tools extract --help
Traceback (most recent call last):
  File "/gnu/store/h5w9i2x61gv36j4hyqwwjj7b5rq5pg6b-umi-tools-0.5.5/bin/.umi_tools-real", line 11, in <module>
    load_entry_point('umi-tools==0.5.5', 'console_scripts', 'umi_tools')()
  File "/gnu/store/h5w9i2x61gv36j4hyqwwjj7b5rq5pg6b-umi-tools-0.5.5/lib/python3.7/site-packages/umi_tools/umi_tools.py", line 54, in main
    module = imp.load_module(command, file, pathname, description)
  File "/gnu/store/ibxxisi81v1v3y5xc3axl4x4rx6jpzw8-python-3.7.0/lib/python3.7/imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "/gnu/store/ibxxisi81v1v3y5xc3axl4x4rx6jpzw8-python-3.7.0/lib/python3.7/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 838, in get_code
TypeError: a bytes-like object is required, not 'str'
~~~

Since `imp` is deprecated, I patched umi_tools.py to use importlib instead:

~~~
diff --git a/umi_tools/umi_tools.py b/umi_tools/umi_tools.py
index 4a507e6..471e707 100644
--- a/umi_tools/umi_tools.py
+++ b/umi_tools/umi_tools.py
@@ -28,7 +28,7 @@ To use a specific tool, type::
 from __future__ import absolute_import
 import os
 import sys
-import imp
+import importlib
 from umi_tools import __version__
 
 
@@ -55,8 +55,7 @@ def main(argv=None):
 
     command = argv[1]
 
-    (file, pathname, description) = imp.find_module(command, [path, ])
-    module = imp.load_module(command, file, pathname, description)
+    module = importlib.import_module("umi_tools." + command, "umi_tools")
     # remove 'umi-tools' from sys.argv
     del sys.argv[0]
     module.main(sys.argv)
~~~

With this patch I can print the help text just fine.  What do you think about this change?

**Comment by TomSmithCGAT** [comment]
Hi @rekado - I hadn't realised that `imp` was deprecated. We should definitely switch to `importlib` in that case. Thanks!

**Comment by TomSmithCGAT** [comment]
The above changes have been made on the {TS}-UpdateKneeMethod branch which will shortly be merged into the master prior to the release of v1.0.0. Thanks again @rekado :+1:
