### ISSUE TITLE
Error when running umi_tools dedup

### ISSUE THREAD

**Issue by shenli-js** [CGATOxford/UMI-tools#341]
Hi,
I got an error when running umi_tools dedup, 
I installed umi-tools by "conda install -c bioconda umi_tools
"

message:
(umitools) [R01@console raw_data]$ umi_tools dedup -h
UMI-Tools: Version 1.0.0
Traceback (most recent call last):
  File "/home/R01/anaconda2/envs/umitools/bin/umi_tools", line 11, in <module>
    sys.exit(main())
  File "/home/R01/anaconda2/envs/umitools/lib/python2.7/site-packages/umi_tools/umi_tools.py", line 58, in main
    module = importlib.import_module("umi_tools." + command, "umi_tools")
  File "/home/R01/anaconda2/envs/umitools/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/R01/anaconda2/envs/umitools/lib/python2.7/site-packages/umi_tools/dedup.py", line 70, in <module>
    import umi_tools.Utilities as U
ImportError: No module named Utilities

Dose any body kown how to fix it?
thanks for your help!
shen

**Comment by IanSudbery** [comment]
This usually means you are using python 2 rather than three, but conda
shouldn't have allowed this.

**Comment by shenli-js** [comment]
I fix it when change to miniconda3,thank you very much  @IanSudbery
