### ISSUE TITLE
issues when running umi_tools group

### ISSUE THREAD

**Issue by kevin199011** [CGATOxford/UMI-tools#360]
Hi when I was running the umi_tools group (using below command:
umi_tools group -I align.sorted.bam --extract-umi-method umis --group-out=group --output-bam --log=group.log -S group.bam --per-contig --per-cell --per-gene)
, I received the following error:
Traceback (most recent call last):
  File "/users/km38465/anaconda3/bin/umi_tools", line 11, in <module>
    sys.exit(main())
  File "/users/km38465/anaconda3/lib/python3.7/site-packages/umi_tools/umi_tools.py", line 57, in main
    module.main(sys.argv)
  File "/users/km38465/anaconda3/lib/python3.7/site-packages/umi_tools/group.py", line 265, in main
    gene = read.get_tag(gene_tag)
  File "pysam/libcalignedsegment.pyx", line 2395, in pysam.libcalignedsegment.AlignedSegment.get_tag
  File "pysam/libcalignedsegment.pyx", line 2435, in pysam.libcalignedsegment.AlignedSegment.get_tag
TypeError: expected bytes, NoneType found

My pysam version is 0.15.3 and umi_tools version 1.0.0.
Could you help to figure out why? Thank you!

Kevin

**Comment by IanSudbery** [comment]
You are using `--per-gene` mode, but you havn't told `umi_tools` how to work out which gene each read is assigned to. There are two options: either `--per-contig`, where the contig contains the name of the gene (this will be the case if you've aligned to the transcriptome rather than the genome), or `--gene-tag=XX` where `XX` is a tag on each read contains the gene a read has been aligned to (usually assigned using featureCounts).

**Comment by kevin199011** [comment]
Thank you for the quick reply. I was using the --per-contig option, which shows the above error message. However, if I manually add a genetag field and use the --gene-tag option, the error is gone. please see below for a small example. Thank you!

Best
[test.sorted.zip](https://github.com/CGATOxford/UMI-tools/files/3497762/test.sorted.zip)

Kevin

**Comment by IanSudbery** [comment]
Sorry, missed that. I can see the problem. I'll try to sort a fix as soon as possible. 

BTW, i'm not sure you are using the most recent version

**Comment by TomSmithCGAT** [comment]
Hi @kevin199011 - Did you get to the bottom of this? If not and this is still an issue, I can take a look at the example.

**Comment by TomSmithCGAT** [comment]
Closing due to inactivity
