### ISSUE TITLE
Error while running UMI-tools

### ISSUE THREAD

**Issue by ofranlab** [CGATOxford/UMI-tools#367]
Hi,

I tried to follow the example you provided. After executing this command:

umi_tools extract --stdin=example.fastq.gz --bc-pattern=NNNNNNNNN --log=processed.log --stdout processed.fastq.gz

I encountered this error:

Traceback (most recent call last):
File "/usr/local/bin/umi_tools", line 5, in <module>
from pkg_resources import load_entry_point
File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
File "/usr/local/lib/python3.4/dist-packages/setuptools-10.0-py3.4.egg/pkg_resources/__init__.py", line 2957, in <module>
File "/usr/local/lib/python3.4/dist-packages/setuptools-10.0-py3.4.egg/pkg_resources/__init__.py", line 567, in _build_master
File "/usr/local/lib/python3.4/dist-packages/setuptools-10.0-py3.4.egg/pkg_resources/__init__.py", line 876, in require
File "/usr/local/lib/python3.4/dist-packages/setuptools-10.0-py3.4.egg/pkg_resources/__init__.py", line 761, in resolve
pkg_resources.DistributionNotFound: matplotlib

Nevertheless, matplotlib is installed on our server, and according to pip it is updated. Did anyone else encountered this problem or has any ideas for a solution?

Thank you so much.
Best,
Sapir

**Comment by IanSudbery** [comment]
How did you install UMI-tools?

**Comment by ofranlab** [comment]
I used
sudo pip3 install umi_tools

Somehow, after unistalling and re-installing both umi_tools and matplotlib, it works. Thank you so much :)
