### ISSUE TITLE
one question about umi-tools

### ISSUE THREAD

**Issue by haiwangxingkong** [CGATOxford/UMI-tools#368]
i had successfully installed umm-tools in my PC, but when i operate ' extract the UMIs ' under the guidance from web ' https://umi-tools.readthedocs.io/en/latest/QUICK_START.html ', there were always one mistake blocking this step.
the question is:
after starting ' $ umi_tools extract --stdin=example.fastq.gz --bc-pattern=NNNNNNNNN --log=processed.log --stdout processed.fastq.gz ', the process was :
 Traceback (most recent call last):
  File "/usr/local/bin/umi_tools", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/umi_tools/umi_tools.py", line 58, in main
    module = importlib.import_module("umi_tools." + command, "umi_tools")
  File "/usr/local/Cellar/python@2/2.7.16_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/lib/python2.7/site-packages/umi_tools/extract.py", line 158, in <module>
    import umi_tools.extract_methods as extract_methods
  File "/usr/local/lib/python2.7/site-packages/umi_tools/extract_methods.py", line 7, in <module>
    import umi_tools.Utilities as U
ImportError: No module named Utilities>

So, what the problem of "ImportError: No module named Utilities", any solutions to solve this problem?

sincerely, Xiao.

**Comment by IanSudbery** [comment]
Dear Xiao,

This problem. Is caused by trying to run UMI-tools on Python 2.7. We
dropped support for python 2.7 in version 1.0.0.
We recommend using python 3. The easiest way to do this is while not
disrupting your current python 2.7 environment is to run UMI-tools from a
python 3 conda environment. If you really need to continue using python
2.7, please install version 0.5.5.

**Comment by TomSmithCGAT** [comment]
I'm closing this issue due to inactivity. Please re-open if this has not been resolved.
