### ISSUE TITLE
YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated,

### ISSUE THREAD

**Issue by yueyangtime** [CGATOxford/UMI-tools#371]
hello! I have finished installed the UMItools, but there was an error when I ```$ nosetests tests/test_umi_tools.py```, the error just like this:

```
/home/fuanhua/tools/UMI-tools-master/tests/test_umi_tools.py:240: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  tool_tests = yaml.load(open(fn))
FFFFFFFFFFFFFFFFFFFFFFFFFF

FAIL: umi_tools.py/dedup_single_chrom

Traceback (most recent call last):
  File "/home/fuanhua/anaconda3/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/fuanhua/tools/UMI-tools-master/tests/test_umi_tools.py", line 202, in check_script
    ok_(not fail, msg)
AssertionError: error in statement: /bin/bash -c 'umi_tools count -L test.log  --random-seed=123456789 --method=directional --gene-tag=XF --skip-tags-regex="^[__|Unassigned]" --per-cell --extract-umi-method=umis --stdin=/home/fuanhua/tools/UMI-tools-master/tests/chr19_gene_tags.bam > /tmp/tmpOAkXMP/stdout'; stderr=Traceback (most recent call last):
  File "/home/fuanhua/.local/bin/umi_tools", line 11, in <module>
    load_entry_point('umi-tools==1.0.0', 'console_scripts', 'umi_tools')()
  File "/home/fuanhua/.local/lib/python2.7/site-packages/umi_tools-1.0.0-py2.7-linux-x86_64.egg/umi_tools/umi_tools.py", line 58, in main
    module = importlib.import_module("umi_tools." + command, "umi_tools")
  File "/home/fuanhua/anaconda3/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/fuanhua/.local/lib/python2.7/site-packages/umi_tools-1.0.0-py2.7-linux-x86_64.egg/umi_tools/count.py", line 46, in <module>
    import umi_tools.Utilities as U
ImportError: No module named Utilities```

so, how to solve this problem?

**Comment by IanSudbery** [comment]
Hi,

You are getting this error because you are trying to run UMI-tools under python 2.7. As of version 1.0.0 we only support python 3. 

Since you are already using anaconda, it should be easy to create a python3 environment and install UMI-tools there using conda. 

Ian

**Comment by yueyangtime** [comment]
Dear Ian,
Thanks wery much, now it works under python 3.5. I mistook the environment.

but, the test restult is FAILD:
```FAIL: umi_tools.py/whitelist_scrb_seq
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/nose-1.0.0-py3.5.egg/nose/case.py", line 188, in runTest
    self.test(*self.arg)
  File "/home/fuanhua/tools/UMI-tools-1.0.0/tests/test_umi_tools.py", line 202, in check_script
    ok_(not fail, msg)
  File "/usr/local/lib/python3.5/dist-packages/nose-1.0.0-py3.5.egg/nose/tools.py", line 25, in ok_
    assert expr, msg
AssertionError: files /tmp/tmplvmctkiv/stdout and tests/indrop_whitelist_ed_above_thres_disc.tsv are not the same
/bin/bash -c 'umi_tools whitelist --extract-method=regex --bc-pattern="(?P<cell_1>.{8,12})(?P<discard_2>GAGTGATTGCTTGTGACGCCTT)(?P<cell_3>.{8})(?P<umi_1>.{6})T{3}.*" -L test.log  --ed-above-threshold=discard --error-correct-threshold=3 --stdin=/home/fuanhua/tools/UMI-tools-1.0.0/tests/indrop.fastq.1.gz > /tmp/tmplvmctkiv/stdout'
md5: output=526, 039455efa00a5014d0f4092389931702 reference=526, 6e8f83308531a9b6ed9bd50932dd29befirst 10 differences: ACCCGACTTGTTGTCAT	ACCCGACTTATTGTCAT	6	1
ACCCGACTTGCAAGGAC	ACCCGACTTACAAGGAC,ACCCGACTTGCAAGGGA	9	1,1
--
ACCCGACTTTGCAAGGG		9	
ACCCGACTTGTTGTCAT	ACCCGACTTATTGTCAT	6	1
--
GAGAAGGCTTTTAGTCCG		3	
GAGAAGGCTTTCCAGTCC		3	

----------------------------------------------------------------------
Ran 53 tests in 40.127s

FAILED (failures=24)```

Is this normal? Is there any problem here?

sincerely, Yueyang.

**Comment by IanSudbery** [comment]
In order to run the tests you need to set the PYTHONHASHSEED environment
variable. One way to do this is with the testing shell script in the root
to the repo.

**Comment by TomSmithCGAT** [comment]
I'm closing this issue due in inactivity. Please re-open if it has not been resolved.
