### ISSUE TITLE
ValueError: fetch called on bamfile without index

### ISSUE THREAD

**Issue by yueli711** [CGATOxford/UMI-tools#389]
**Hello,**

I tried to download the example.bam and followed:
https://umi-tools.readthedocs.io/en/latest/QUICK_START.html.

Thanks in advance for any help!
Best,

Yue
`li@li-HP-Pavilion-Desktop-590-p0xxx:~$ umi_tools dedup -I example.bam.1 --output-stats=deduplicated -S deduplicated.bam`

`2019-12-18 16:32:52,732 INFO command: dedup -I example.bam.1 --output-stats=deduplicated -S deduplicated.bam
Traceback (most recent call last):
  File "/home/li/.local/bin/umi_tools", line 11, in <module>
    load_entry_point('umi-tools==1.0.0', 'console_scripts', 'umi_tools')()
  File "/home/li/.local/lib/python3.6/site-packages/umi_tools/umi_tools.py", line 61, in main
    module.main(sys.argv)
  File "/home/li/.local/lib/python3.6/site-packages/umi_tools/dedup.py", line 235, in main
    inreads = infile.fetch()
  File "pysam/libcalignmentfile.pyx", line 1088, in pysam.libcalignmentfile.AlignmentFile.fetch
ValueError: fetch called on bamfile without index`
`

**Comment by IanSudbery** [comment]
As it says in the QUICK_START, you need to index the file first with `samtools index`.

As in `samtools index example.bam`

**Comment by yueli711** [comment]
Hello, lanSudbery,

Thank you so much for your great help!

Thank you again!

Best,

Yue

By the command above, SAMPLE.bam.bai will be generated.
