### ISSUE TITLE
module error

### ISSUE THREAD

**Issue by Polalpha** [CGATOxford/UMI-tools#406]
After installing UMI_tools on my Mac from pip I found it has a module error even when I was running --help option as below. Can anybody please help? Thanks!
umi_tools extract --help
UMI-Tools: Version 1.0.1
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/bin/umi_tools", line 10, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/umi_tools/umi_tools.py", line 58, in main
    module = importlib.import_module("umi_tools." + command, "umi_tools")
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/umi_tools/extract.py", line 158, in <module>
    import umi_tools.extract_methods as extract_methods
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/umi_tools/extract_methods.py", line 7, in <module>
    import umi_tools.Utilities as U
ImportError: No module named Utilities

**Comment by IanSudbery** [comment]
Hi,
It looks from this like you are trying to run umi_tools in python 2.7, but as of version 1, we only support python 3. You will need to either install umi_tools in a python 3 environment, or revert to umi_tools 0.5.5. The easiest way to install umi_tools in a python 3 environment is through conda.

**Comment by Polalpha** [comment]
Thank you Ian! I tried to create python 3 environment but wasn't successful. I got the 0.5.5 instead and this version works. One more question, are you aware of any consensus making process that can be done through UMI_tools? Thank you! P

**Comment by IanSudbery** [comment]
No. Its on our list, for the next version if we get funding, but at the moment its not something we implement. 

`umi_tools group` will output all reads, with a group tag which could then be postprocessed.

**Comment by TomSmithCGAT** [comment]
Closing due to inactivity. Please re-open if required
