### ISSUE TITLE
umi_tools count error

### ISSUE THREAD

**Issue by dwkarjosukarso** [CGATOxford/UMI-tools#412]
Hi,
I am trying out this tool since the output is more suitable for some downstream analysis.
I am following the single cell tutorial and it is going fine until I reached the last part, umi_tools count. 

I kept running into the following error: 

```
> ERROR
> Traceback (most recent call last):
>   File "/home/karjosukarso/anaconda3/envs/scSplit/bin/umi_tools", line 11, in <module>
>     sys.exit(main())
>   File "/home/karjosukarso/anaconda3/envs/scSplit/lib/python3.6/site-packages/umi_tools/umi_tools.py", line 61, in main
>     module.main(sys.argv)
>   File "/home/karjosukarso/anaconda3/envs/scSplit/lib/python3.6/site-packages/umi_tools/count.py", line 143, in main
>     for bundle, key, status in bundle_iterator(inreads):
>   File "/home/karjosukarso/anaconda3/envs/scSplit/lib/python3.6/site-packages/umi_tools/sam_methods.py", line 457, in __call__
>     if re.search(self.options.skip_regex, assigned):
>   File "/home/karjosukarso/anaconda3/envs/scSplit/lib/python3.6/re.py", line 182, in search
>     return _compile(pattern, flags).search(string)
> TypeError: expected string or bytes-like object
```

the command I used:
`umi_tools count --wide-format-cell-counts --extract-umi-method=tag --umi-tag=UB  --cell-tag=CB --per-gene --gene-tag=XT --assigned-status-tag=XS  --per-cell -I $sBAM -S $COUNTS`

a glimpse of my sBAM file:
```
NS500173:399:HJ2MCBGX5:3:13402:11495:8162       16      chr1    14400   1       63M     *       0       0       TAGGTTTCTGCTCAGTTCTTTATTGATTGGTGTGCCGTTTTCTCTGGAAGCCTCTTAAGAACA /EEE<EEEEEEEEEEEEEEEEEEEEEEEAEE/AEAEEEEEEEEEEEEEEEEEEEEEEEAAAAA        CB:Z:AACACGCA   UB:Z:ATCTGCTA   MD:Z:1T61       XG:i:0  NM:i:1  XM:i:1  XN:i:0  XO:i:0  AS:i:-5 XS:i:-5 YT:Z:UU XS:Z:Unassigned_Ambiguity
NS500173:399:HJ2MCBGX5:4:22505:14430:18084      16      chr1    14403   0       59M1D4M *       0       0       TTTTCTGCTCAGTTCTTTATTGATTGGTGTGCCGCTTTCTCTGGAAGCCTCTTAAGAACAAGT EEEE//E6EEEA/6AEE/EEEEEEAEE/AAEEAEEEEEEEEEE<EEEEEEEEEEEEEEAAAAA        CB:Z:ATGGCACT   UB:Z:TAACGAGT   MD:Z:0G33T24^A0C3       XG:i:1  NM:i:4  XM:i:3  XN:i:0  XO:i:1  AS:i:-23        XS:i:-23        YT:Z:UU XS:Z:Unassigned_Ambiguity
NS500173:399:HJ2MCBGX5:3:12611:1757:7381        16      chr1    14408   1       59M1D4M *       0       0       TGCTCAGTTCTTTATTGATTGGTGTGCCGTTTTCTCTGGAAGCCTCTTAAGAACACAGTGCGC EEE/E/A/EAEEAEEEEEEEAAEEE6EEA/AE/EAAA6AEEEEA/EEAEEEEEEE/EEAAAAA        CB:Z:CTATAGGC   UB:Z:ATATGTAG   MD:Z:59^G4      XG:i:1  NM:i:1  XM:i:0  XN:i:0  XO:i:1  AS:i:-8 XS:i:-8 YT:Z:UU XS:Z:Unassigned_Ambiguity
NS500173:399:HJ2MCBGX5:4:23506:25312:9959       16      chr1    14409   1       63M     *       0       0       GCTCAGTTCTTTATTGATTGGTGTGCCGTTTTCTCTGGAAGCCTCTTAAGAACACAGTGGCGC EEEAEEAAEEAEEAEEEE/EE<EEEAEE/E/EEEEEEEEEEEEEEEEEAEEEEEEEEEAAAAA        CB:Z:ATGGCACT   UB:Z:TAACGAGT   MD:Z:63 XG:i:0  NM:i:0  XM:i:0  XN:i:0  XO:i:0  AS:i:0  XS:i:0  YT:Z:UU XS:Z:Unassigned_Ambiguity
NS500173:399:HJ2MCBGX5:1:22304:17453:14172      16      chr1    14413   1       63M     *       0       0       AGTTCTTTATTGATTGGTGTGCCGTTTTCTCTGGAAGCCTCTTAAGAACACAGTGGCACAGGC EEEEEEEEEE/EEEEEEEEEEEEE<AEEEAEEEEEEEEEEEEEEEEEEEEEEE/AEEEAAAAA        CB:Z:ACGCGTAA   UB:Z:CTTTGGCG   MD:Z:57G5       XG:i:0  NM:i:1  XM:i:1  XN:i:0  XO:i:0  AS:i:-5 XS:i:-5 YT:Z:UU XS:Z:Assigned   XN:i:1  XT:Z:ENSG00000227232.5
NS500173:399:HJ2MCBGX5:2:22103:19200:8941       16      chr1    14439   1       63M     *       0       0       TTCTCTGGAAGCCTCTTAAGAACACAGTGGCGCAGGCTGGGTGGAGCCGTCCCCCCATGAAGC EEEEEEAEEEEEEEEEEEAEEEEEEEE<<<<<EA<AEE<AAA<AE<AA/EEEEEEEEEAAAAA        CB:Z:AGCTTCAC   UB:Z:GGTACATA   MD:Z:59G3       XG:i:0  NM:i:1  XM:i:1  XN:i:0  XO:i:0  AS:i:-5 XS:i:-5 YT:Z:UU XS:Z:Assigned   XN:i:1  XT:Z:ENSG00000227232.5
NS500173:399:HJ2MCBGX5:3:21401:10098:6733       16      chr1    14439   1       63M     *       0       0       TGCTCTGGAAGCCTCTTAAGAACACAGTGGCGCAGGCTGGGTGGAGCCGTCCCCCCATGGAGC 6/E//AEE<<EE//AEEE/EE//EEEE</EA//AEEE6E/EEE/EE/AEEEEE6EEEEAAAAA        CB:Z:ATGGCACT   UB:Z:TAACGAGT   MD:Z:1T61       XG:i:0  NM:i:1  XM:i:1  XN:i:0  XO:i:0  AS:i:-3 XS:i:-3 YT:Z:UU XS:Z:Assigned   XN:i:1  XT:Z:ENSG00000227232.5
NS500173:399:HJ2MCBGX5:3:23607:23995:6333       16      chr1    14439   1       63M     *       0       0       TTCTCTGGAAGCCTCTTAAGAACACAGTGGCGCAGGCTGGGTGGAGCCGTCCCCCCATGGAGC <A6/6/A<AA/AA/A6</EA/A/AAEA//E6EEEAEEEEEE/EEEEAEEEEEEEEEEEAAAAA        CB:Z:ATGGCACT   UB:Z:TAACGAGT   MD:Z:63 XG:i:0  NM:i:0  XM:i:0  XN:i:0  XO:i:0  AS:i:0  XS:i:0  YT:Z:UU XS:Z:Assigned   XN:i:1  XT:Z:ENSG00000227232.5
NS500173:399:HJ2MCBGX5:4:11501:3772:10401       16      chr1    14439   1       63M     *       0       0       TTCTCTGGAAGCCTCTTAAGAACACAGTGGCGCAGGCTGGGTGGAGCCGTCCCCCCATGGAGT E<E<EEAEEAE/EEEEEE<E/A/</EE<AE<6E/EA<<</<EE<AEA/<EE6AEAAEEAAAAA        CB:Z:CAGCTTTG   UB:Z:GATGGACG   MD:Z:62C0       XG:i:0  NM:i:1  XM:i:1  XN:i:0  XO:i:0  AS:i:-5 XS:i:-5 YT:Z:UU XS:Z:Assigned   XN:i:1  XT:Z:ENSG00000227232.5
NS500173:399:HJ2MCBGX5:4:22602:15630:19801      16      chr1    14439   1       63M     *       0       0       TTCTCTGGAAGCCTCTTAAGAACACAGTGGCGCAGGCTGGGTGGAGCCGTCCCCCCATGGAGC //EAE/EEEEEEEAAA<EE<EEEEEEE/<AAEEEEEEEEEE/EAEEEEEEEEEEEEEEAAAAA        CB:Z:ATGGCACT   UB:Z:TAACGAGT   MD:Z:63 XG:i:0  NM:i:0  XM:i:0  XN:i:0  XO:i:0  AS:i:0  XS:i:0  YT:Z:UU XS:Z:Assigned   XN:i:1  XT:Z:ENSG00000227232.5
```

Do you maybe know what could have gone wrong?

Thank you.

Best,
Dyah

**Comment by TomSmithCGAT** [comment]
Looking at those BAM entries, you appear to have two 'XS' tags, one with a numeric value and another with the assigned status. At a guess, I would say this is probably where the problem stems from. Where does the`XS:i` tag originate from?

**Comment by dwkarjosukarso** [comment]
I checked my files and the XS:i is already there when I converted my SAM file to BAM.

Alignment was done with Bowtie2
bowtie2 --threads 4 -x $REF -U $EXTRACTED_FASTQ1,$EXTRACTED_FASTQ2 -S $SAM
 
and then:
samtools view -S -b $SAM >  $BAM

The BAM file was then used for featureCounts and umi_tools count as per tutorial.

**Comment by Shineshine** [comment]
I met the same problem when I used bowtie2 for alignment.
If the question has been solved，please let me know.

Thank you.

**Comment by TomSmithCGAT** [comment]
Just to summarise here, the issue is that the XS tag is not defined in the SAM format (https://en.wikipedia.org/wiki/SAM_(file_format)) and can be used by tools for whatever annotation is desired. Both Bowtie2 (http://bowtie-bio.sourceforge.net/bowtie2/manual.shtml) and featureCounts (https://bioconductor.org/packages/release/bioc/vignettes/Rsubread/inst/doc/SubreadUsersGuide.pdf) use the XS tag. Since neither tool appears to allow the user to define a different tag, they are incompatible if the XS tag is required by a downstream tool. 

I think the only way around this would be to insert an intermediate step after Bowtie to replace the XS tag.
