### ISSUE TITLE
after installing with pip3 I get following error: "pkg_resources.DistributionNotFound: The 'python-dateutil>=2.7.3' distribution was not found and is required by pandas"

### ISSUE THREAD

**Issue by bkaczkowski** [CGATOxford/UMI-tools#429]
Hi,
It seems that when installed with pip3 and running on python3 it looks for python2 library ('python-dateutil>=2.7.3')
the full error message is here
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 574, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 892, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 783, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (python-dateutil 2.6.1 (/usr/lib/python3/dist-packages), Requirement.parse('python-dateutil>=2.7.3'), {'pandas'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/umi_tools", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3088, in <module>
    @_call_aside
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3072, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3101, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 576, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 589, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 778, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'python-dateutil>=2.7.3' distribution was not found and is required by pandas

**Comment by IanSudbery** [comment]
Hi

dateutils is not one of our requirements. It looks like it is coming from
pandas. In fact, while dateutil 2.7.3 looks like a python 2 module, i think
that is a co-incidence of version numbering, as the PyPI page for dateutils
says that 2.7.3 is compatible with python3. (
https://pypi.org/project/python-dateutil/2.7.3/)

My best guess is that you have something installed that has pinned dateutil
to 2.6.1 (see the first part of the error message), but pandas requires it
to be at least 2.7.3. Finding out what it is that is pinned dateutil to
2.6.1 might be painful. You could force an installation of dateutil 2.7.3
separately. Of course, that might break whatever package it was that was
requiring 2.6.1. The alternative would be to set up different virtualenvs
or use conda environments to have both 2.6.1 and 2.7.3 installed at the
same time.

Ian

**Comment by bkaczkowski** [comment]
Hi Ian,
Thanks a lot for your detailed reply and clarifying my misunderstanding! It was very helpful!

Actually, when I run 
`pip3 install python-dateutil` 
 separately, it did install the latest version (python_dateutil-2.8.1)

After that the installation was successful. 
`pip3 install umi_tools`  

Best
Bogumil
