### ISSUE TITLE
/libk5crypto.so.3: symbol krb5int_utf8s_to_ucs2les, version krb5support_0_MIT not defined in file libkrb5support.so.0 with link time reference

### ISSUE THREAD

**Issue by windtalker6** [CGATOxford/UMI-tools#430]
I used to install umi_tools under the python 2.7, when I run:
umi_tools extract --help

there comes the error:
UMI-Tools: Version 1.0.0
Traceback (most recent call last):
  File "/home/wubin/miniconda3/bin/umi_tools", line 11, in <module>
    sys.exit(main())
  File "/home/wubin/miniconda3/lib/python2.7/site-packages/umi_tools/umi_tools.py", line 58, in main
    module = importlib.import_module("umi_tools." + command, "umi_tools")
  File "/home/wubin/miniconda3/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/wubin/miniconda3/lib/python2.7/site-packages/umi_tools/extract.py", line 158, in <module>
    import umi_tools.extract_methods as extract_methods
  File "/home/wubin/miniconda3/lib/python2.7/site-packages/umi_tools/extract_methods.py", line 7, in <module>
    import umi_tools.Utilities as U
ImportError: No module named Utilities
======================================================================

then I installed umi_tools under the python 3.5.5,  when I check it, no problem found:
======================================================================
$pip install --user "umi_tools"
DEPRECATION: Python 3.5 reached the end of its life on September 13th, 2020. Please upgrade your Python as Python 3.5 is no longer maintained. pip 21.0 will drop support for Python 3.5 in January 2021. pip 21.0 will remove support for this functionality.
Requirement already satisfied: umi_tools in /home/wubin/miniconda3/envs/umi_tools/lib/python3.5/site-packages (0.5.5)
Requirement already satisfied: setuptools>=1.1 in /home/wubin/miniconda3/envs/umi_tools/lib/python3.5/site-packages (from umi_tools) (40.4.3)
Requirement already satisfied: numpy>=1.7 in /home/wubin/miniconda3/envs/umi_tools/lib/python3.5/site-packages (from umi_tools) (1.11.3)
Requirement already satisfied: pandas>=0.12.0 in /home/wubin/miniconda3/envs/umi_tools/lib/python3.5/site-packages (from umi_tools) (0.23.4)
Requirement already satisfied: future in /home/wubin/miniconda3/envs/umi_tools/lib/python3.5/site-packages (from umi_tools) (0.16.0)
Requirement already satisfied: regex in /home/wubin/miniconda3/envs/umi_tools/lib/python3.5/site-packages (from umi_tools) (2016.6.24)
Requirement already satisfied: scipy in /home/wubin/miniconda3/envs/umi_tools/lib/python3.5/site-packages (from umi_tools) (0.19.0)
Requirement already satisfied: matplotlib in /home/wubin/miniconda3/envs/umi_tools/lib/python3.5/site-packages (from umi_tools) (1.5.1)
Requirement already satisfied: python-dateutil>=2.5.0 in /home/wubin/miniconda3/envs/umi_tools/lib/python3.5/site-packages (from pandas>=0.12.0->umi_tools) (2.8.1)
Requirement already satisfied: pytz>=2011k in /home/wubin/miniconda3/envs/umi_tools/lib/python3.5/site-packages (from pandas>=0.12.0->umi_tools) (2020.1)
Requirement already satisfied: cycler in /home/wubin/miniconda3/envs/umi_tools/lib/python3.5/site-packages (from matplotlib->umi_tools) (0.10.0)
Requirement already satisfied: pyparsing!=2.0.4,>=1.5.6 in /home/wubin/miniconda3/envs/umi_tools/lib/python3.5/site-packages (from matplotlib->umi_tools) (2.4.7)
Requirement already satisfied: six>=1.5 in /home/wubin/miniconda3/envs/umi_tools/lib/python3.5/site-packages (from python-dateutil>=2.5.0->pandas>=0.12.0->umi_tools) (1.15.0)

======================================================================

but when I run :
$umi_tools dedup --help
Traceback (most recent call last):
  File "/home/wubin/miniconda3/envs/umi_tools/bin/umi_tools", line 11, in <module>
    sys.exit(main())
  File "/home/wubin/miniconda3/envs/umi_tools/lib/python3.5/site-packages/umi_tools/umi_tools.py", line 54, in main
    module = imp.load_module(command, file, pathname, description)
  File "/home/wubin/miniconda3/envs/umi_tools/lib/python3.5/imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "/home/wubin/miniconda3/envs/umi_tools/lib/python3.5/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 697, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/wubin/miniconda3/envs/umi_tools/lib/python3.5/site-packages/umi_tools/dedup.py", line 61, in <module>
    import pysam
  File "/home/wubin/miniconda3/envs/umi_tools/lib/python3.5/site-packages/pysam/__init__.py", line 5, in <module>
    from pysam.libchtslib import *
ImportError: /home/wubin/miniconda3/envs/umi_tools/lib/././libk5crypto.so.3: symbol krb5int_utf8s_to_ucs2les, version krb5support_0_MIT not defined in file libkrb5support.so.0 with link time reference
==============================================================================

the same error occured when I tried other commands of umi_tools.

how can I solve this?

**Comment by IanSudbery** [comment]
This looks like a problem with a system library required for `chtslib`, which in turn is required for `pysam`. You could try updating your libk5crypto version. 

However, I see that you are using a miniconda environment, but installing using pip. Any particular reason you are not installing with conda?

**Comment by windtalker6** [comment]
well, I just updated my python to 3.7, then it works
