### ISSUE TITLE
Impossible to launch UMI_tools

### ISSUE THREAD

**Issue by wanaga3166** [CGATOxford/UMI-tools#468]
Hi,

I tried to install umi_tools with this command line: 

`conda install -c bioconda -c conda-forge umi_tools`

which return:

`Collecting package metadata (current_repodata.json): done
Solving environment: done

# All requested packages already installed.
`
When I tried to do `umi_tools --help`, I obtained this error answer:

`Traceback (most recent call last):
  File "/home/my_computer/miniconda3/envs/snakemake/bin/umi_tools", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/home/my_computer/miniconda3/envs/snakemake/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3243, in <module>
    def _initialize_master_working_set():
  File "/home/my_computer/miniconda3/envs/snakemake/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3226, in _call_aside
    f(*args, **kwargs)
  File "/home/my_computer/miniconda3/envs/snakemake/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3255, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/my_computer/miniconda3/envs/snakemake/lib/python3.9/site-packages/pkg_resources/__init__.py", line 568, in _build_master
    ws.require(__requires__)
  File "/home/my_computer/miniconda3/envs/snakemake/lib/python3.9/site-packages/pkg_resources/__init__.py", line 886, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/my_computer/miniconda3/envs/snakemake/lib/python3.9/site-packages/pkg_resources/__init__.py", line 772, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'umi-tools==0.2.3' distribution was not found and is required by the application
`
I use conda and snakemake. 

How I can fix that ? 

Thank you for your help.

Benoit

**Comment by IanSudbery** [comment]
umi-tools 0.2.3 is a very old version of umi-tool. I think you are getting
this becausae bioconda doesn't yet build umi-tools for python 3.9. You can
test this with

conda install -c bioconda -c conda-forge umi-tools==1.1

It will probably complain that it can't do it, or it will try to install a
different version of python.

I don't actually know of any reason why umi-tools shouldn't work with
python 3.9, so you could try installing it a different way, starting with
pip.

conda remove umi-tools
pip install umi-tools

If that doesn't work, you could try downloading the code from the github,
and installing by running

python setup.py install

from the code directory.


Either that, or allow conda to change to a python version that bioconda
supports.

Hope that is some help.

**Comment by wanaga3166** [comment]
Thank you Ian for your help. I installed umi-tools (1.1.1) with pip and it worked :-)
