### ISSUE TITLE
Obtaining error for parsing fastq file

### ISSUE THREAD

**Issue by kpatankar** [CGATOxford/UMI-tools#482]
Greetings,

When running UMI-tools extract on paired end fastq files I am getting following error

```
Traceback (most recent call last):
  File "/data/bin/miniconda2/bin/umi_tools", line 11, in <module>
    sys.exit(main())
  File "/data/bin/miniconda2/lib/python2.7/site-packages/umi_tools/umi_tools.py", line 46, in main
    module.main(sys.argv)
  File "/data/bin/miniconda2/lib/python2.7/site-packages/umi_tools/extract.py", line 419, in main
    for read1, read2 in izip(read1s, read2s):
  File "/data/bin/miniconda2/lib/python2.7/site-packages/umi_tools/extract.py", line 165, in fastqIterate
    raise ValueError("parsing error: expected '@' in line %s" % line1)
ValueError: parsing error: expected '@' in line
```
Would appreciate help resolving it.

**Comment by IanSudbery** [comment]
Hi, 
UMI-tools expects the title line in a fastq file to start with an `@`. The error is produced because the line being processed should be the start of a new fastq record, which should start with `@`, but doesn't. 

The error message should contain the line that is missing the @ symbol. The fact that there is a blank after "in line" suggests that the line is blank. Perhaps your fastq file has an extra blank line at the end?

**Comment by IanSudbery** [comment]
Did you manage to get this sorted?
