### ISSUE TITLE
dedup.py needs deduplicated BAM-file to be indexed?

### ISSUE THREAD

**Issue by JeroenMerks** [CGATOxford/UMI-tools#50]
Dear developers.
I'm testing your awesome toolkit, but I don't know what to do with the following problem:

**Used parameters**
```
python dedup.py \
-I xxx_sorted.bam \
-S xxx_dedup_chr19.bam \
--paired \
--edit-distance-threshold 1 \
--output-stats xxx_dedup_chr19 \
--chrom chr19 \
-v 5
```
**Traceback**
```
...
2016-10-24 13:54:43,213 DEBUG Outputted 780000
2016-10-24 13:55:03,757 DEBUG Dumping 857871 mates for contig chr19
2016-10-24 13:57:13,608 DEBUG 3997 mates remaining
2016-10-24 13:57:13,608 INFO Searching for mates for 3997 unmatched alignments
Traceback (most recent call last):
  File "./UMI-tools-0.2.3-edited/umi_tools/dedup.py", line 1145, in <module>
    sys.exit(main(sys.argv))
  File "./UMI-tools-0.2.3-edited/umi_tools/dedup.py", line 1050, in main
    outfile.close()
  File "./UMI-tools-0.2.3-edited/umi_tools/dedup.py", line 309, in close
    for read in self.outfile.fetch(start=pos, end=pos+1, tid=chrom):
  File "pysam/calignmentfile.pyx", line 874, in pysam.calignmentfile.AlignmentFile.fetch (pysam/calignmentfile.c:10986)
ValueError: fetch called on bamfile without index
```
**Files in directory**
- xxx_sorted.bam
- xxx_sorted.bam.bai
- xxx_dedup_chr19.bam

**Software versions**
UMI-tools v0.2.3
pysam 0.8.4

**Tried**
Adding the until_eof=True flag to the self.outfile.fetch() function (to allow fetching if there's no index), but then I get an error that the BAM-file is truncated.

**Comment by IanSudbery** [comment]
Hi Jeroen,

It should be calling fetch on the infile, not the outfile. Don't know how that got in. Can you try the code in the [fetch-called-on-outfile](https://github.com/CGATOxford/UMI-tools/tree/fetch-called-on-outfile) branch. Are you comfortable pulling the code off git?

Cheers,
Ian
---

**Comment by JeroenMerks** [comment]
That fixed it.
Thank you  for your quick reply and fix!
