### ISSUE TITLE
TypeError: 'encoding' is an invalid keyword argument for this function

### ISSUE THREAD

**Issue by yueli8** [CGATOxford/UMI-tools#643]
Hello,

Thank you for developing so nice software!

I tried to install `UMI-tools-master` in my `Ubuntu 20.04.6`, but got this error: ` TypeError: 'encoding' is an invalid keyword argument for this function`.

Thank you in advance for your great help!

Best,

Yue

```
-P330:~/UMI-tools-master$ python setup.py install --user
running install
running bdist_egg
running egg_info
writing requirements to umi_tools.egg-info/requires.txt
writing umi_tools.egg-info/PKG-INFO
writing top-level names to umi_tools.egg-info/top_level.txt
writing dependency_links to umi_tools.egg-info/dependency_links.txt
writing entry points to umi_tools.egg-info/entry_points.txt
reading manifest file 'umi_tools.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'umi_tools.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/umi_tools
copying build/lib.linux-x86_64-2.7/umi_tools/Documentation.py -> build/bdist.linux-x86_64/egg/umi_tools
copying build/lib.linux-x86_64-2.7/umi_tools/group.py -> build/bdist.linux-x86_64/egg/umi_tools
copying build/lib.linux-x86_64-2.7/umi_tools/_dedup_umi.c -> build/bdist.linux-x86_64/egg/umi_tools
copying build/lib.linux-x86_64-2.7/umi_tools/count_tab.py -> build/bdist.linux-x86_64/egg/umi_tools
copying build/lib.linux-x86_64-2.7/umi_tools/extract_methods.py -> build/bdist.linux-x86_64/egg/umi_tools
copying build/lib.linux-x86_64-2.7/umi_tools/network.py -> build/bdist.linux-x86_64/egg/umi_tools
copying build/lib.linux-x86_64-2.7/umi_tools/Utilities.py -> build/bdist.linux-x86_64/egg/umi_tools
copying build/lib.linux-x86_64-2.7/umi_tools/sam_methods.py -> build/bdist.linux-x86_64/egg/umi_tools
copying build/lib.linux-x86_64-2.7/umi_tools/version.py -> build/bdist.linux-x86_64/egg/umi_tools
copying build/lib.linux-x86_64-2.7/umi_tools/whitelist_methods.py -> build/bdist.linux-x86_64/egg/umi_tools
copying build/lib.linux-x86_64-2.7/umi_tools/count.py -> build/bdist.linux-x86_64/egg/umi_tools
copying build/lib.linux-x86_64-2.7/umi_tools/umi_tools.py -> build/bdist.linux-x86_64/egg/umi_tools
copying build/lib.linux-x86_64-2.7/umi_tools/prepare-for-rsem.py -> build/bdist.linux-x86_64/egg/umi_tools
copying build/lib.linux-x86_64-2.7/umi_tools/extract.py -> build/bdist.linux-x86_64/egg/umi_tools
copying build/lib.linux-x86_64-2.7/umi_tools/dedup.py -> build/bdist.linux-x86_64/egg/umi_tools
copying build/lib.linux-x86_64-2.7/umi_tools/whitelist.py -> build/bdist.linux-x86_64/egg/umi_tools
copying build/lib.linux-x86_64-2.7/umi_tools/__init__.py -> build/bdist.linux-x86_64/egg/umi_tools
copying build/lib.linux-x86_64-2.7/umi_tools/_dedup_umi.pyx -> build/bdist.linux-x86_64/egg/umi_tools
copying build/lib.linux-x86_64-2.7/umi_tools/umi_methods.py -> build/bdist.linux-x86_64/egg/umi_tools
copying build/lib.linux-x86_64-2.7/umi_tools/_dedup_umi.so -> build/bdist.linux-x86_64/egg/umi_tools
byte-compiling build/bdist.linux-x86_64/egg/umi_tools/Documentation.py to Documentation.pyc
byte-compiling build/bdist.linux-x86_64/egg/umi_tools/group.py to group.pyc
byte-compiling build/bdist.linux-x86_64/egg/umi_tools/count_tab.py to count_tab.pyc
byte-compiling build/bdist.linux-x86_64/egg/umi_tools/extract_methods.py to extract_methods.pyc
byte-compiling build/bdist.linux-x86_64/egg/umi_tools/network.py to network.pyc
byte-compiling build/bdist.linux-x86_64/egg/umi_tools/Utilities.py to Utilities.pyc
byte-compiling build/bdist.linux-x86_64/egg/umi_tools/sam_methods.py to sam_methods.pyc
byte-compiling build/bdist.linux-x86_64/egg/umi_tools/version.py to version.pyc
byte-compiling build/bdist.linux-x86_64/egg/umi_tools/whitelist_methods.py to whitelist_methods.pyc
byte-compiling build/bdist.linux-x86_64/egg/umi_tools/count.py to count.pyc
byte-compiling build/bdist.linux-x86_64/egg/umi_tools/umi_tools.py to umi_tools.pyc
byte-compiling build/bdist.linux-x86_64/egg/umi_tools/prepare-for-rsem.py to prepare-for-rsem.pyc
byte-compiling build/bdist.linux-x86_64/egg/umi_tools/extract.py to extract.pyc
byte-compiling build/bdist.linux-x86_64/egg/umi_tools/dedup.py to dedup.pyc
byte-compiling build/bdist.linux-x86_64/egg/umi_tools/whitelist.py to whitelist.pyc
byte-compiling build/bdist.linux-x86_64/egg/umi_tools/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/umi_tools/umi_methods.py to umi_methods.pyc
creating stub loader for umi_tools/_dedup_umi.so
byte-compiling build/bdist.linux-x86_64/egg/umi_tools/_dedup_umi.py to _dedup_umi.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying umi_tools.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying umi_tools.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying umi_tools.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying umi_tools.egg-info/entry_points.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying umi_tools.egg-info/not-zip-safe -> build/bdist.linux-x86_64/egg/EGG-INFO
copying umi_tools.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying umi_tools.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
writing build/bdist.linux-x86_64/egg/EGG-INFO/native_libs.txt
creating 'dist/umi_tools-1.1.5-py2.7-linux-x86_64.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing umi_tools-1.1.5-py2.7-linux-x86_64.egg
removing '/home/yueli/.local/lib/python2.7/site-packages/umi_tools-1.1.5-py2.7-linux-x86_64.egg' (and everything under it)
creating /home/yueli/.local/lib/python2.7/site-packages/umi_tools-1.1.5-py2.7-linux-x86_64.egg
Extracting umi_tools-1.1.5-py2.7-linux-x86_64.egg to /home/yueli/.local/lib/python2.7/site-packages
umi-tools 1.1.5 is already the active version in easy-install.pth
Installing umi_tools script to /home/yueli/.local/bin

Installed /home/yueli/.local/lib/python2.7/site-packages/umi_tools-1.1.5-py2.7-linux-x86_64.egg
Processing dependencies for umi-tools==1.1.5
Searching for regex
Reading https://pypi.org/simple/regex/
Downloading https://files.pythonhosted.org/packages/7a/db/5ddc89851e9cc003929c3b08b9b88b429459bf9acbf307b4556d51d9e49b/regex-2024.5.15.tar.gz#sha256=d3ee02d9e5f482cc8309134a91eeaacbdd2261ba111b0fef3748eeb4913e6a2c
Best match: regex 2024.5.15
Processing regex-2024.5.15.tar.gz
Writing /tmp/easy_install-dpXt2z/regex-2024.5.15/setup.cfg
Running regex-2024.5.15/setup.py -q bdist_egg --dist-dir /tmp/easy_install-dpXt2z/regex-2024.5.15/egg-dist-tmp-XIwN89
Traceback (most recent call last):
  File "setup.py", line 121, in <module>
    zip_safe=False,
  File "/home/yueli/.local/lib/python2.7/site-packages/setuptools/__init__.py", line 162, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/home/yueli/.local/lib/python2.7/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/home/yueli/.local/lib/python2.7/site-packages/setuptools/command/install.py", line 117, in do_egg_install
    cmd.run(show_deprecation=False)
  File "/home/yueli/.local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 424, in run
    self.easy_install(spec, not self.no_deps)
  File "/home/yueli/.local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 666, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/home/yueli/.local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 713, in install_item
    self.process_distribution(spec, dist, deps)
  File "/home/yueli/.local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 758, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "/home/yueli/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 782, in resolve
    replace_conflicting=replace_conflicting
  File "/home/yueli/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1065, in best_match
    return self.obtain(req, installer)
  File "/home/yueli/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1077, in obtain
    return installer(requirement)
  File "/home/yueli/.local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 685, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/home/yueli/.local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 711, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/home/yueli/.local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 896, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/home/yueli/.local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1164, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/home/yueli/.local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1150, in run_setup
    run_setup(setup_script, args)
  File "/home/yueli/.local/lib/python2.7/site-packages/setuptools/sandbox.py", line 253, in run_setup
    raise
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/yueli/.local/lib/python2.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/yueli/.local/lib/python2.7/site-packages/setuptools/sandbox.py", line 166, in save_modules
    saved_exc.resume()
  File "/home/yueli/.local/lib/python2.7/site-packages/setuptools/sandbox.py", line 141, in resume
    six.reraise(type, exc, self._tb)
  File "/home/yueli/.local/lib/python2.7/site-packages/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/home/yueli/.local/lib/python2.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/home/yueli/.local/lib/python2.7/site-packages/setuptools/sandbox.py", line 250, in run_setup
    _execfile(setup_script, ns)
  File "/home/yueli/.local/lib/python2.7/site-packages/setuptools/sandbox.py", line 45, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-dpXt2z/regex-2024.5.15/setup.py", line 6, in <module>
    
  File "/home/yueli/.local/lib/python2.7/site-packages/setuptools/sandbox.py", line 419, in _open
    return _open(path, mode, *args, **kw)
TypeError: 'encoding' is an invalid keyword argument for this function

```

**Comment by IanSudbery** [comment]
Hi Yue,

You are running python 2.7 in your Ubuntu setup. UMI-tools requires python 3. The oldest version which we test against is 3.7, but 3.6 probably still works (although 3.8 is the oldest version that is not officially end-of-life according to the python foundation).

The easiest way to ensure you have the right dependencies for UMI-tools and install from the github master branch is  to run

```
$ conda [create -n ENVNAME | install] -c bioconda -c conda-forge UMI-tools --only-deps
$ conda activate ENVNAME
$ git clone https://github.com/CGATOxford/UMI-tools.git
$ cd UMI-tools
$ python setup.py install
```

The conda call either creates an env, or installs into the current env, all of the dependencies for UMI-tools, without actaully installing UMI-tools itself.

**Comment by yueli8** [comment]
Hello IanSudbery,

Thank you so much for your quick response!

```
sudo apt-get remove python2.7
sudo apt-get remove --auto-remove pyhton2.7
sudo apt-get purge python2.7
sudo apt-get purge --auto-remove python2.7

```
```
P330:~/UMI-tools-master$ python3 setup.py install --user
running install
running bdist_egg
running egg_info
writing umi_tools.egg-info/PKG-INFO
writing dependency_links to umi_tools.egg-info/dependency_links.txt
writing entry points to umi_tools.egg-info/entry_points.txt
writing requirements to umi_tools.egg-info/requires.txt
writing top-level names to umi_tools.egg-info/top_level.txt
reading manifest file 'umi_tools.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'umi_tools.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/umi_tools
copying build/lib.linux-x86_64-3.8/umi_tools/Documentation.py -> build/bdist.linux-x86_64/egg/umi_tools
copying build/lib.linux-x86_64-3.8/umi_tools/group.py -> build/bdist.linux-x86_64/egg/umi_tools
copying build/lib.linux-x86_64-3.8/umi_tools/_dedup_umi.c -> build/bdist.linux-x86_64/egg/umi_tools
copying build/lib.linux-x86_64-3.8/umi_tools/count_tab.py -> build/bdist.linux-x86_64/egg/umi_tools
copying build/lib.linux-x86_64-3.8/umi_tools/extract_methods.py -> build/bdist.linux-x86_64/egg/umi_tools
copying build/lib.linux-x86_64-3.8/umi_tools/network.py -> build/bdist.linux-x86_64/egg/umi_tools
copying build/lib.linux-x86_64-3.8/umi_tools/Utilities.py -> build/bdist.linux-x86_64/egg/umi_tools
copying build/lib.linux-x86_64-3.8/umi_tools/sam_methods.py -> build/bdist.linux-x86_64/egg/umi_tools
copying build/lib.linux-x86_64-3.8/umi_tools/version.py -> build/bdist.linux-x86_64/egg/umi_tools
copying build/lib.linux-x86_64-3.8/umi_tools/whitelist_methods.py -> build/bdist.linux-x86_64/egg/umi_tools
copying build/lib.linux-x86_64-3.8/umi_tools/count.py -> build/bdist.linux-x86_64/egg/umi_tools
copying build/lib.linux-x86_64-3.8/umi_tools/umi_tools.py -> build/bdist.linux-x86_64/egg/umi_tools
copying build/lib.linux-x86_64-3.8/umi_tools/prepare-for-rsem.py -> build/bdist.linux-x86_64/egg/umi_tools
copying build/lib.linux-x86_64-3.8/umi_tools/extract.py -> build/bdist.linux-x86_64/egg/umi_tools
copying build/lib.linux-x86_64-3.8/umi_tools/dedup.py -> build/bdist.linux-x86_64/egg/umi_tools
copying build/lib.linux-x86_64-3.8/umi_tools/whitelist.py -> build/bdist.linux-x86_64/egg/umi_tools
copying build/lib.linux-x86_64-3.8/umi_tools/_dedup_umi.cpython-38-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/egg/umi_tools
copying build/lib.linux-x86_64-3.8/umi_tools/__init__.py -> build/bdist.linux-x86_64/egg/umi_tools
copying build/lib.linux-x86_64-3.8/umi_tools/_dedup_umi.pyx -> build/bdist.linux-x86_64/egg/umi_tools
copying build/lib.linux-x86_64-3.8/umi_tools/umi_methods.py -> build/bdist.linux-x86_64/egg/umi_tools
byte-compiling build/bdist.linux-x86_64/egg/umi_tools/Documentation.py to Documentation.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/umi_tools/group.py to group.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/umi_tools/count_tab.py to count_tab.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/umi_tools/extract_methods.py to extract_methods.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/umi_tools/network.py to network.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/umi_tools/Utilities.py to Utilities.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/umi_tools/sam_methods.py to sam_methods.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/umi_tools/version.py to version.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/umi_tools/whitelist_methods.py to whitelist_methods.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/umi_tools/count.py to count.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/umi_tools/umi_tools.py to umi_tools.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/umi_tools/prepare-for-rsem.py to prepare-for-rsem.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/umi_tools/extract.py to extract.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/umi_tools/dedup.py to dedup.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/umi_tools/whitelist.py to whitelist.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/umi_tools/__init__.py to __init__.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/umi_tools/umi_methods.py to umi_methods.cpython-38.pyc
creating stub loader for umi_tools/_dedup_umi.cpython-38-x86_64-linux-gnu.so
byte-compiling build/bdist.linux-x86_64/egg/umi_tools/_dedup_umi.py to _dedup_umi.cpython-38.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying umi_tools.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying umi_tools.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying umi_tools.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying umi_tools.egg-info/entry_points.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying umi_tools.egg-info/not-zip-safe -> build/bdist.linux-x86_64/egg/EGG-INFO
copying umi_tools.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying umi_tools.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
writing build/bdist.linux-x86_64/egg/EGG-INFO/native_libs.txt
creating 'dist/umi_tools-1.1.5-py3.8-linux-x86_64.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing umi_tools-1.1.5-py3.8-linux-x86_64.egg
removing '/home/yueli/.local/lib/python3.8/site-packages/umi_tools-1.1.5-py3.8-linux-x86_64.egg' (and everything under it)
creating /home/yueli/.local/lib/python3.8/site-packages/umi_tools-1.1.5-py3.8-linux-x86_64.egg
Extracting umi_tools-1.1.5-py3.8-linux-x86_64.egg to /home/yueli/.local/lib/python3.8/site-packages
umi-tools 1.1.5 is already the active version in easy-install.pth
Installing umi_tools script to /home/yueli/.local/bin

Installed /home/yueli/.local/lib/python3.8/site-packages/umi_tools-1.1.5-py3.8-linux-x86_64.egg
Processing dependencies for umi-tools==1.1.5
Searching for setuptools==45.2.0
Best match: setuptools 45.2.0
Adding setuptools 45.2.0 to easy-install.pth file
Installing easy_install script to /home/yueli/.local/bin

Using /usr/lib/python3/dist-packages
Searching for scipy==1.10.1
Best match: scipy 1.10.1
Adding scipy 1.10.1 to easy-install.pth file

Using /home/yueli/.local/lib/python3.8/site-packages
Searching for regex==2024.5.15
Best match: regex 2024.5.15
Adding regex 2024.5.15 to easy-install.pth file

Using /home/yueli/.local/lib/python3.8/site-packages
Searching for pybktree==1.1
Best match: pybktree 1.1
Adding pybktree 1.1 to easy-install.pth file

Using /home/yueli/.local/lib/python3.8/site-packages
Searching for pandas==2.0.3
Best match: pandas 2.0.3
Adding pandas 2.0.3 to easy-install.pth file

Using /home/yueli/.local/lib/python3.8/site-packages
Searching for numpy==1.24.3
Best match: numpy 1.24.3
Adding numpy 1.24.3 to easy-install.pth file
Installing f2py script to /home/yueli/.local/bin
Installing f2py3 script to /home/yueli/.local/bin
Installing f2py3.8 script to /home/yueli/.local/bin

Using /home/yueli/.local/lib/python3.8/site-packages
Searching for matplotlib==3.7.5
Best match: matplotlib 3.7.5
Adding matplotlib 3.7.5 to easy-install.pth file

Using /home/yueli/.local/lib/python3.8/site-packages
Searching for future==1.0.0
Best match: future 1.0.0
Adding future 1.0.0 to easy-install.pth file
Installing futurize script to /home/yueli/.local/bin
Installing pasteurize script to /home/yueli/.local/bin

Using /home/yueli/.local/lib/python3.8/site-packages
Searching for tzdata==2024.1
Best match: tzdata 2024.1
Adding tzdata 2024.1 to easy-install.pth file

Using /home/yueli/.local/lib/python3.8/site-packages
Searching for python-dateutil==2.9.0.post0
Best match: python-dateutil 2.9.0.post0
Adding python-dateutil 2.9.0.post0 to easy-install.pth file

Using /home/yueli/.local/lib/python3.8/site-packages
Searching for pytz==2024.1
Best match: pytz 2024.1
Adding pytz 2024.1 to easy-install.pth file

Using /home/yueli/.local/lib/python3.8/site-packages
Searching for contourpy==1.1.1
Best match: contourpy 1.1.1
Adding contourpy 1.1.1 to easy-install.pth file

Using /home/yueli/.local/lib/python3.8/site-packages
Searching for Pillow==7.0.0
Best match: Pillow 7.0.0
Adding Pillow 7.0.0 to easy-install.pth file

Using /usr/lib/python3/dist-packages
Searching for packaging==24.0
Best match: packaging 24.0
Adding packaging 24.0 to easy-install.pth file

Using /home/yueli/.local/lib/python3.8/site-packages
Searching for importlib-resources==6.4.0
Best match: importlib-resources 6.4.0
Adding importlib-resources 6.4.0 to easy-install.pth file

Using /home/yueli/.local/lib/python3.8/site-packages
Searching for cycler==0.12.1
Best match: cycler 0.12.1
Adding cycler 0.12.1 to easy-install.pth file

Using /home/yueli/.local/lib/python3.8/site-packages
Searching for kiwisolver==1.4.5
Best match: kiwisolver 1.4.5
Adding kiwisolver 1.4.5 to easy-install.pth file

Using /home/yueli/.local/lib/python3.8/site-packages
Searching for pyparsing==3.1.2
Best match: pyparsing 3.1.2
Adding pyparsing 3.1.2 to easy-install.pth file

Using /home/yueli/.local/lib/python3.8/site-packages
Searching for fonttools==4.51.0
Best match: fonttools 4.51.0
Adding fonttools 4.51.0 to easy-install.pth file
Installing fonttools script to /home/yueli/.local/bin
Installing pyftmerge script to /home/yueli/.local/bin
Installing pyftsubset script to /home/yueli/.local/bin
Installing ttx script to /home/yueli/.local/bin

Using /home/yueli/.local/lib/python3.8/site-packages
Searching for six==1.14.0
Best match: six 1.14.0
Adding six 1.14.0 to easy-install.pth file

Using /usr/lib/python3/dist-packages
Searching for zipp==3.17.0
Best match: zipp 3.17.0
Adding zipp 3.17.0 to easy-install.pth file

Using /home/yueli/.local/lib/python3.8/site-packages
Finished processing dependencies for umi-tools==1.1.5

```

**Comment by TomSmithCGAT** [comment]
@yueli8 - From the above output, it looks like the installation worked OK after updating to python 3.8 so I'm closing this issue
