### ISSUE TITLE
ModuleNotFoundError: No module named 'umi_tools' with Python 3.9

### ISSUE THREAD

**Issue by MelinaKlostermann** [CGATOxford/UMI-tools#668]
**Describe the bug**
I am trying to use umi_tools dedup but get the error 

from umi_tools.umi_tools import main
ModuleNotFoundError: No module named 'umi_tools'

**To Reproduce**
I build a conda environment with the following yaml file:
```
#name: umi_tools2
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - pysam=0.16.0.1
  - umi_tools=1.1.5
```
 when I am in the environment and use conda list this is what is in the environment:

```
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
brotli                    1.1.0                hb9d3cd8_2    conda-forge
brotli-bin                1.1.0                hb9d3cd8_2    conda-forge
bzip2                     1.0.8                h4bc722e_7    conda-forge
c-ares                    1.34.2               heb4867d_0    conda-forge
ca-certificates           2024.8.30            hbcca054_0    conda-forge
certifi                   2024.8.30          pyhd8ed1ab_0    conda-forge
contourpy                 1.3.0            py39h74842e3_2    conda-forge
cycler                    0.12.1             pyhd8ed1ab_0    conda-forge
fonttools                 4.54.1           py39h9399b63_1    conda-forge
freetype                  2.12.1               h267a509_2    conda-forge
future                    1.0.0              pyhd8ed1ab_0    conda-forge
importlib-resources       6.4.5              pyhd8ed1ab_0    conda-forge
importlib_resources       6.4.5              pyhd8ed1ab_0    conda-forge
jpeg                      9e                   h0b41bf4_3    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
kiwisolver                1.4.7            py39h74842e3_0    conda-forge
krb5                      1.20.1               hf9c8cef_0    conda-forge
lcms2                     2.12                 hddcbb42_0    conda-forge
ld_impl_linux-64          2.43                 h712a8e2_2    conda-forge
libblas                   3.9.0           25_linux64_openblas    conda-forge
libbrotlicommon           1.1.0                hb9d3cd8_2    conda-forge
libbrotlidec              1.1.0                hb9d3cd8_2    conda-forge
libbrotlienc              1.1.0                hb9d3cd8_2    conda-forge
libcblas                  3.9.0           25_linux64_openblas    conda-forge
libcurl                   7.87.0               h6312ad2_0    conda-forge
libdeflate                1.21                 h4bc722e_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 hd590300_2    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc                    14.2.0               h77fa898_1    conda-forge
libgcc-ng                 14.2.0               h69a702a_1    conda-forge
libgfortran               14.2.0               h69a702a_1    conda-forge
libgfortran-ng            14.2.0               h69a702a_1    conda-forge
libgfortran5              14.2.0               hd5240d6_1    conda-forge
libgomp                   14.2.0               h77fa898_1    conda-forge
liblapack                 3.9.0           25_linux64_openblas    conda-forge
libnghttp2                1.51.0               hdcd2b5c_0    conda-forge
libnsl                    2.0.1                hd590300_0    conda-forge
libopenblas               0.3.28          pthreads_h94d23a6_1    conda-forge
libpng                    1.6.43               h2797004_0    conda-forge
libsqlite                 3.46.0               hde9e2c9_0    conda-forge
libssh2                   1.10.0               haa6b8db_3    conda-forge
libstdcxx                 14.2.0               hc0a3c3a_1    conda-forge
libstdcxx-ng              14.2.0               h4852527_1    conda-forge
libtiff                   4.2.0                hf544144_3    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libwebp-base              1.4.0                hd590300_0    conda-forge
libzlib                   1.2.13               h4ab18f5_6    conda-forge
matplotlib-base           3.9.2            py39h16632d1_2    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
ncurses                   6.5                  he02047a_1    conda-forge
numpy                     2.0.2            py39h9cb892a_0    conda-forge
olefile                   0.47               pyhd8ed1ab_0    conda-forge
openjpeg                  2.4.0                hb52868f_1    conda-forge
openssl                   1.1.1w               hd590300_0    conda-forge
packaging                 24.1               pyhd8ed1ab_0    conda-forge
pandas                    2.2.3            py39h3b40f6f_1    conda-forge
pillow                    8.2.0            py39hf95b381_1    conda-forge
pip                       24.3.1             pyh8b19718_0    conda-forge
pybktree                  1.1                pyh9f0ad1d_0    conda-forge
pyparsing                 3.2.0              pyhd8ed1ab_1    conda-forge
pysam                     0.16.0.1         py39h051187c_3    bioconda
python                    3.9.15          h47a2c10_0_cpython    conda-forge
python-dateutil           2.9.0              pyhd8ed1ab_0    conda-forge
python-tzdata             2024.2             pyhd8ed1ab_0    conda-forge
python_abi                3.9                      5_cp39    conda-forge
pytz                      2024.1             pyhd8ed1ab_0    conda-forge
qhull                     2020.2               h434a139_5    conda-forge
readline                  8.2                  h8228510_1    conda-forge
regex                     2024.11.6        py39h8cd3c5a_0    conda-forge
scipy                     1.13.1           py39haf93ffa_0    conda-forge
setuptools                75.3.0             pyhd8ed1ab_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
tk                        8.6.13          noxft_h4845f30_101    conda-forge
tzdata                    2024b                hc8b5060_0    conda-forge
umi_tools                 1.1.5            py39hff71179_3    bioconda
unicodedata2              15.1.0           py39h8cd3c5a_1    conda-forge
wheel                     0.44.0             pyhd8ed1ab_0    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
zipp                      3.20.2             pyhd8ed1ab_0    conda-forge
zlib                      1.2.13               h4ab18f5_6    conda-forge
zstd                      1.5.6                ha6fb4c9_0    conda-forge

```

The following commands all produce the same error for me:

```

umi_tools dedup -I {input.bam} -L {params.log} -S {output.bam} --extract-umi-method read_id --method unique
umi_tools -h
umi_tools dedup -h

```

**Expected behavior**
It should find umi_tools.

**Environment**
 - Debian GNU/Linux 12 (bookworm)
 - UMI-tools version 1.1.5
 - Conda installation as described above

**Comment by IanSudbery** [comment]
Can you post the output of
$ which python

and

$ python -c "import pysam; print(pysam.__file__)"


Ian Sudbery
(He/Him)
Senior Lecturer in Bioinformatics,
Sheffield Institute for Nucleic Acids,
School of Biosciences,
The University of Sheffield.

web: www.sudlab.co.uk
Tel: 0114 222 2738
Twitter: IanSudbery
Show Calendar Availability
<https://calendar.google.com/calendar/u/0?cid=aS5zdWRiZXJ5QHNoZWZmaWVsZC5hYy51aw>

**Comment by MelinaKlostermann** [comment]
which python
/home/mklostermann/applications/anaconda3/envs/minimal_R_v2/bin/python

python -c "import pysam; print(pysam.__file__)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'pysam'

**Comment by MelinaKlostermann** [comment]
which python
/home/mklostermann/applications/anaconda3/envs/minimal_R_v2/bin/python

python -c "import pysam; print(pysam.__file__)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'pysam'

However, which python does not point to the python version inside the environment. With

conda list python
I get the correct one:
# packages in environment at /media/storage/home/mklostermann/projects/07_processed_published_data/SF3B1_K562_encode_but_SRA_download/00_raw/.snakemake/conda/a2c3eb5ae7f1c59d6ae2e69792415259_:
#
# Name                    Version                   Build  Channel
python                    3.9.15          h47a2c10_0_cpython    conda-forge
python-dateutil           2.9.0              pyhd8ed1ab_0    conda-forge
python-tzdata             2024.2             pyhd8ed1ab_0    conda-forge
python_abi                3.9                      5_cp39    conda-forge

**Comment by IanSudbery** [comment]
Looks like the python you are getting is not the same one as conda believes
it is active environment. I notice that the one pointed to by "which
python" is an anaconda one. Is it possible that you have both a miniconda
and an anaconda installation active?

Ian Sudbery
(He/Him)
Senior Lecturer in Bioinformatics,
Sheffield Institute for Nucleic Acids,
School of Biosciences,
The University of Sheffield.

web: www.sudlab.co.uk
Tel: 0114 222 2738
Twitter: IanSudbery
Show Calendar Availability
<https://calendar.google.com/calendar/u/0?cid=aS5zdWRiZXJ5QHNoZWZmaWVsZC5hYy51aw>

**Comment by MelinaKlostermann** [comment]
Thanks! It wasn't anaconda and miniconda but I hade several conda environments on top of each other, which caused the usage of the wrong python instance! It works now :)

**Comment by IanSudbery** [comment]
I'm closing this issue. Please feel free to reopen, or open a new one if needed.
