### ISSUE TITLE
Error running dedup and group

### ISSUE THREAD

**Issue by kliere** [CGATOxford/UMI-tools#79]
Both scripts tell me that the module Utilities is not found/installed, which, however, is. 

umi_tools dedup -I /Users/karsten/Downloads/example.bam --output-stats=deduplicated -S deduplicated.bam
Traceback (most recent call last):
  File "/usr/local/bin/umi_tools", line 11, in <module>
    load_entry_point('umi-tools==0.3.6', 'console_scripts', 'umi_tools')()
  File "/usr/local/lib/python2.7/site-packages/umi_tools/umi_tools.py", line 43, in main
    module = imp.load_module(command, file, pathname, description)
  File "/usr/local/lib/python2.7/site-packages/umi_tools/dedup.py", line 227, in <module>
    import Utilities as U
ImportError: No module named Utilities

Same happens if running umi_tools dedup --help or umi_tools group --help

Any insights, what I might missing here?

Best,

Karsten

**Comment by IanSudbery** [comment]
Hi Karsten,

That’s strange … Utilites is part of UMI-tools and should have been
installed when you install UMI-tools. How did you install the software? Was
it from PyPI/conda/source?

Can you post the output of `ls
/usr/local/lib/python2.7/site-packages/umi_tools/dedup.py`?

Cheers.

**Comment by kliere** [comment]
Hi Ian, 

I forgot some infos: UMI-Tools was installed on macOS 10.11 via pip install. as far as I can see, all scripts are in the uni_tools folder. However, here is the report:
$ ls /usr/local/lib/python2.7/site-packages/umi_tools/dedup.py
/usr/local/lib/python2.7/site-packages/umi_tools/dedup.py

$ ls /usr/local/lib/python2.7/site-packages/umi_tools/
Utilities.py	_dedup_umi.pyx	extract.pyc	network.pyc	umi_tools.pyc
Utilities.pyc	dedup.py	group.py	umi_methods.py	version.py
__init__.py	dedup.pyc	group.pyc	umi_methods.pyc	version.pyc
__init__.pyc	extract.py	network.py	umi_tools.py

Cheers,

k.

**Comment by TomSmithCGAT** [comment]
Can you try running the following import statements in a python session and see what you get:
```
import umi_tools.Utilities
import Utilities
```

**Comment by kliere** [comment]
Hope I got it right:

Python 2.7.13 (default, Dec 17 2016, 23:03:43) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import umi_tools.Utilities
>>> import Utilities
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named Utilities
>>>

**Comment by IanSudbery** [comment]
@TomSmithCGAT Look like a bunch of import statements are collected together until the same try statement. I suspect one of the other imports is failing, and thus triggering the py3 style relative import. We should seperate these imports out into seperate trys

@kliere 
Can you try:
import umi_tools.network as network
import umi_tools.umi_methods as umi_methods

**Comment by kliere** [comment]
>>> import umi_tools.network as network
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/umi_tools/network.py", line 24, in <module>
    from _dedup_umi import edit_distance
  File "/usr/local/lib/python2.7/site-packages/pyximport/pyximport.py", line 445, in load_module
    language_level=self.language_level)
  File "/usr/local/lib/python2.7/site-packages/pyximport/pyximport.py", line 234, in load_module
    exec("raise exc, None, tb", {'exc': exc, 'tb': tb})
  File "/usr/local/lib/python2.7/site-packages/pyximport/pyximport.py", line 216, in load_module
    inplace=build_inplace, language_level=language_level)
  File "/usr/local/lib/python2.7/site-packages/pyximport/pyximport.py", line 192, in build_module
    reload_support=pyxargs.reload_support)
  File "/usr/local/lib/python2.7/site-packages/pyximport/pyxbuild.py", line 102, in pyx_to_dll
    dist.run_commands()
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python2.7/site-packages/Cython/Distutils/old_build_ext.py", line 185, in run
    _build_ext.build_ext.run(self)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/usr/local/lib/python2.7/site-packages/Cython/Distutils/old_build_ext.py", line 192, in build_extensions
    ext.sources = self.cython_sources(ext.sources, ext)
  File "/usr/local/lib/python2.7/site-packages/Cython/Distutils/old_build_ext.py", line 345, in cython_sources
    full_module_name=module_name)
  File "/usr/local/lib/python2.7/site-packages/Cython/Compiler/Main.py", line 684, in compile
    return compile_single(source, options, full_module_name)
  File "/usr/local/lib/python2.7/site-packages/Cython/Compiler/Main.py", line 634, in compile_single
    return run_pipeline(source, options, full_module_name)
  File "/usr/local/lib/python2.7/site-packages/Cython/Compiler/Main.py", line 494, in run_pipeline
    err, enddata = Pipeline.run_pipeline(pipeline, source)
  File "/usr/local/lib/python2.7/site-packages/Cython/Compiler/Pipeline.py", line 340, in run_pipeline
    data = phase(data)
  File "/usr/local/lib/python2.7/site-packages/Cython/Compiler/Pipeline.py", line 53, in generate_pyx_code_stage
    module_node.process_implementation(options, result)
  File "/usr/local/lib/python2.7/site-packages/Cython/Compiler/ModuleNode.py", line 137, in process_implementation
    self.generate_c_code(env, options, result)
  File "/usr/local/lib/python2.7/site-packages/Cython/Compiler/ModuleNode.py", line 387, in generate_c_code
    f = open_new_file(result.c_file)
  File "/usr/local/lib/python2.7/site-packages/Cython/Utils.py", line 65, in open_new_file
    return codecs.open(path, "w", encoding="ISO-8859-1")
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/codecs.py", line 896, in open
    file = __builtin__.open(filename, mode, buffering)
ImportError: Building module umi_tools._dedup_umi failed: ["IOError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/site-packages/umi_tools/_dedup_umi.c'\n"]

**Comment by kliere** [comment]
>>> import umi_tools.umi_methods as umi_methods
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/umi_tools/umi_methods.py", line 30, in <module>
    from _dedup_umi import edit_distance
  File "/usr/local/lib/python2.7/site-packages/pyximport/pyximport.py", line 445, in load_module
    language_level=self.language_level)
  File "/usr/local/lib/python2.7/site-packages/pyximport/pyximport.py", line 234, in load_module
    exec("raise exc, None, tb", {'exc': exc, 'tb': tb})
  File "/usr/local/lib/python2.7/site-packages/pyximport/pyximport.py", line 216, in load_module
    inplace=build_inplace, language_level=language_level)
  File "/usr/local/lib/python2.7/site-packages/pyximport/pyximport.py", line 192, in build_module
    reload_support=pyxargs.reload_support)
  File "/usr/local/lib/python2.7/site-packages/pyximport/pyxbuild.py", line 102, in pyx_to_dll
    dist.run_commands()
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python2.7/site-packages/Cython/Distutils/old_build_ext.py", line 185, in run
    _build_ext.build_ext.run(self)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/usr/local/lib/python2.7/site-packages/Cython/Distutils/old_build_ext.py", line 192, in build_extensions
    ext.sources = self.cython_sources(ext.sources, ext)
  File "/usr/local/lib/python2.7/site-packages/Cython/Distutils/old_build_ext.py", line 345, in cython_sources
    full_module_name=module_name)
  File "/usr/local/lib/python2.7/site-packages/Cython/Compiler/Main.py", line 684, in compile
    return compile_single(source, options, full_module_name)
  File "/usr/local/lib/python2.7/site-packages/Cython/Compiler/Main.py", line 634, in compile_single
    return run_pipeline(source, options, full_module_name)
  File "/usr/local/lib/python2.7/site-packages/Cython/Compiler/Main.py", line 494, in run_pipeline
    err, enddata = Pipeline.run_pipeline(pipeline, source)
  File "/usr/local/lib/python2.7/site-packages/Cython/Compiler/Pipeline.py", line 340, in run_pipeline
    data = phase(data)
  File "/usr/local/lib/python2.7/site-packages/Cython/Compiler/Pipeline.py", line 53, in generate_pyx_code_stage
    module_node.process_implementation(options, result)
  File "/usr/local/lib/python2.7/site-packages/Cython/Compiler/ModuleNode.py", line 137, in process_implementation
    self.generate_c_code(env, options, result)
  File "/usr/local/lib/python2.7/site-packages/Cython/Compiler/ModuleNode.py", line 387, in generate_c_code
    f = open_new_file(result.c_file)
  File "/usr/local/lib/python2.7/site-packages/Cython/Utils.py", line 65, in open_new_file
    return codecs.open(path, "w", encoding="ISO-8859-1")
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/codecs.py", line 896, in open
    file = __builtin__.open(filename, mode, buffering)
ImportError: Building module umi_tools._dedup_umi failed: ["IOError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/site-packages/umi_tools/_dedup_umi.c'\n"]

**Comment by IanSudbery** [comment]
bingo! 

Looks like the cython compiler doesn't have permission to write to the install directory. Did you install with `sudo`? Can you try running:

```
sudo umi_tools dedup --help
```
If this works the first time, _dedup_umi.c should be compliled and you should then be able to run without `sudo`

**Comment by kliere** [comment]
Yep, I did install with sudo. ---

Yay, indeed, now everything seems to run. Great. Thank you so much!

Cheers,

k.

**Comment by IanSudbery** [comment]
@TomSmithCGAT One for the install guide?

**Comment by TomSmithCGAT** [comment]
@IanSudbery 
Thanks for sorting this and spotting the lazy try except. 

I suspect this may be a mac-specific issue since the introduction of System Integrity Protection.
